=== datasektionen/hurryscurry/resources/rpu/schemas/schema.characters.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {},
    "id": "characters-schema",
    "properties": {
        "area": {
            "id": "/properties/area",
            "type": "string"
        },
        "events": {
            "id": "/properties/events",
            "items": {
                "additionalProperties": false,
                "id": "/properties/events/items",
                "properties": {
                    "comment": {
                        "id": "/properties/events/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/events/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/events/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "id": "/properties/id",
            "type": "string"
        },
        "location": {
            "id": "/properties/location",
            "type": "string"
        },
        "missions": {
            "id": "/properties/missions",
            "items": {
                "additionalProperties": false,
                "id": "/properties/missions/items",
                "properties": {
                    "comment": {
                        "id": "/properties/missions/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/missions/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/missions/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "persona": {
            "id": "/properties/persona",
            "type": "string"
        },
        "props": {
            "id": "/properties/props",
            "type": "string"
        }
    },
    "required": [
        "persona",
        "name",
        "area",
        "events",
        "location",
        "props",
        "id",
        "missions"
    ],
    "type": "object"
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/chewbacca.json
{
    "id": "chewbacca",
    "name": "Chewbacca",
    "location": "Se översiktsdokument på Drive",
    "area": "Karaokebaren i Corellia System",
    "persona": "Chewbacca, även kallad Chewie, är hyfsat glad och lurvig 200-år gammal Wookie som är bästis med Han Solo. Han ska se riktigt hårig ut och gärna vara målad i samma stil med ansiktsfärg för att få den rätta looken. Du kommer aldrig prata riktig svenska, utan bara göra Wookie-ljud.",
    "props": "En dator att köra karaoke ifrån, 12 st pappersflygplan med serienummer på de som hör till 1000-års uppdraget, 12 st autografbilder och ett lämpligt bord för armbrytning.",
    "missions": [
        {
            "id": "1000arsservice:0",
            "comment": "Både nØllan och du har varit på jakt efter en hyperdrive motivator för att kunna reparera falken. Men svag som du är för rymdsynthar så fastnade du vid en karaokebar och blev distraherad från att ta med reservdelen till Deppo som är mekaniker. nØllan kommer till dig för att hämta reservdelen, men först måste de sjunga en duett med dig på SingStar! När ni har sjungit en låt av dignitet så får nØllan ta med sig ett av de pappersplan som finns på plats. De ska då ta med sig planet tillbaka till Deppo för att kunna avsluta uppdraget. Prata och sjung gärna så mycket du kan och var helt oförståelig när du pratar med nØllan! Till det här uppdraget borde det gå att instruera nØllan vad som ska göras med hjälp av gester och lite humor. ",
            "response": ""
        },
        {
            "id": "stridsteknik:2",
            "comment": "När nØllan kommer för att få en signerad bild på dig till Maz Kanata räcker du fram en av de signerade bilderna du har i din ägo väldigt nöjt och självsäkert.",
            "response": ""
        },
        {
            "id": "kesselrun:1",
            "comment": "När nØllan frågar om Falken informerar du dem att Han Solos vakter har tagit den och att nØllan måste besvara vaktens gåta.",
            "response": ""
        }
    ],
    "events": [
        {
            "id": "negative:9",
            "comment": "nØllan har startat en konflikt på rymd-twitter och du har utmanat de på armbrytning. Om nØllan vinner betalar de inget, om de förlorar betalar de 200 krediter. Hur mycket du vill försöka är upp till dig",
            "response": ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/big_bunji.json
{
    "id": "big_bunji",
    "name": "Big Bunji",
    "location": "Meta",
    "area": "Baren i Mos Eisley",
    "persona": "En tvättäkta rymdskurk. Bunji är oärlig, skum och otrevlig. Gärna klädd i kåpa så att han inte visar ansiktet. Sitter och super eller spelar i Mos Eisley.",
    "props": "14 kuponger för lasersvärd, 14 plastmuggar, en (liten) flaska YES, 14 st ritningar av dödsstjärnan, en penna att signera händelsekortet.",
    "missions": [
        {
            "id": "ritningar:3",
            "comment": "nØllan kommer till Mos Eisley och letar efter någon som har ritningarna till Dödsstjärnan, kan hända att dom frågar direkt efter dig. Var skeptisk mot dem när de frågar efter dig, men få dom inte att leta efter dig i hundra år. När de har lokaliserat dig kommer de att fråga om ritningarna, spela tuff och motvillig men gå med på att avslöja var ritningarna finns för minst 700 krediter (förhandla!). Ritningarna har du nämligen läckt till Wookieleaks.org. (Kan hända att detta inte funkar, då kommer du att sälja pappersritningar istället). Förklara också riktigt otrevligt att de måste få ritningarna godkända av Imperiets Ministeria för Inspektion och Övrig Hantering av Massförstörelsevapen och Laserbazookas i Cloud City. Sen avslöjar du att ritningarna finns på Wookieleaks.org konspiratoriskt",
            "response": ""
        },
        {
            "id": "leia:1",
            "comment": "nØllan har fått veta att du är en väldigt otrevlig typ som hänger i Mos Eisley och att du kanske har hört något om Leia från de som reser genom staden. När nØllan frågar om Leia ska du leda dem till Luke genom att säga något i stil med följande.",
            "response": "Leia? Han Solo beskrev henne som ättrig och bortskämd. Dessutom verkade hon bara bry sig om den där Like, Lajka.. Luke? Ja, i alla fall så var det senaste jag hörde om deras lilla äventyr att prinsessan blev tillfångatagen och Luke hamnade i någon form av knipa. Han håller visst till någonstans djupt nere i Wild Space nu för tiden."
        },
        {
          "id": "lasersvard:2",
          "comment" : "var lite grumlig och ge förslag på olika fullständigt orimliga dealer (ju orimligare desto bättre, typ ni kan få intel för 50 000 krediter) innan du kommer att tänka på att du just nu faktiskt skulle vilja höra lite musik.",
          "response" : "Här i krokarna spelar de bara skräpmusik. Jag skulle vilja höra min favoritmelodi i ljuv stämsång. Om ni letar upp ewoken Latara och ber henne om det vackraste stycket hon i galaxen, tar er tillbaks hit och framträder det för mig, då har ni en deal! Latara brukar hålla till i Cloud City."
    			}
    ],
    "events": [
        {
            "id": "negative:6",
            "comment": "Du har kidnappat nØllans städare. Nu kommer de och betalar lösen. Lösensumman är ca 300 kred. När du fått pengarna ger du en liten plastmugg till nØllan och fyller det med YES. (Detta fungerar sedan som bevis på att uppdraget är slutfört i rebellbasen)",
            "response" : ""
        },
        {
            "id": "negative:7",
            "comment": "Du jobbar också extra som videouthyrare. nØllan kommer för att betala en förseningsavgift för filmen “Tjejen som beamades för mycket”. Det kostar 500 kred. När nØllan har betalat signerar du deras händelsekort.",
            "response" : ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/boba_fett.json
{
    "id": "boba_fett",
    "name": "Boba Fett",
    "location": "Området mellan Arkitekt och Meta",
    "area": "Wild Space",
    "persona": "Klädd i rustning från topp till tå (Blå-grå nyanser). Han ser läskig och grym ut. Bobba är en prisjägare som alltid har sitt vapen nära till hands. Fåordig om man inte betalar för information och då är han saklig och effektiv.",
    "props": "Ca 1500 krediter och en penna att signera händelsekortet med. Utöver det ska du se fett cool ut.",
    "missions": [
        {
            "id": "1000arsservice:1",
            "comment": "nØllan behöver hjälp med att hitta en mekaniker. När din rymdmoped gick sönder nyligen fick du hjälp av mekanikern Deppo i Junkfort Station. Rekommendera honom, han verkade vara en lagom pålitlig typ.",
            "response": "Jag reparerade min rymdmoped hos mekanikern Deppo i Junkfort Station vid Nar Shaddaa."
        },
        {
            "id": "solo:3",
            "comment": "Luke har tipsat nØllan om att fråga dig när det kommer till Han Solo och/eller svensexan (som du tyckte var episk) så säger du följande:",
            "response": "“Svensexa. Juste, vi drog till Ice-bar! Jarjar och Pitbull drog hem tidigt, klena som de är. Luke hittade en riktigt snygg wookiebrud och drog hem, så det var bara jag och Han Solo kvar. Sen fastnade Han Solo med tungan på en vägg. Så jag gick hem, ingen har sett honom sedan dess. Konstigt. Ni kan hitta Ice-bar, som också går under namnet Cryochamber 5, i Corellia System.”"
        },
        {
            "id": "prisjagare:1",
            "comment": "nØllan ska ta på sig ett uppdrag som prisjägare och du är deras uppdragsgivare. När de kommer och söker dig säger du: ",
            "response": "“Jag vill att Joruus C'baoth skall röjas ur vägen. Leverera hans huvud till min kumpan i rebellbasen. Jag har hört att R2D2 vet var han befinner sig. Namnet Joruus C'baoth kanske kan väcka robotens minne till liv. R2D2 såg jag senast i baren i Mos Eisley.“"
        }
    ],
    "events": [
        {
            "id": "positive:4",
            "comment": "Sprickskytt: Om nØllan har händelsekortet prickskyttetävling ska du gratulera dem och belöna dem med 300 kred. Signera sedan kortet.",
            "response" : ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/leia.json
{
    "id": "leia",
    "name": "Leia",
    "location": "E33",
    "area": "Cell 2187, Detention Block AA-23 - Borderland Regions",
    "persona": "Leia Organa är en prinsessa från Alderaan. En vacker, ganska mager vit kvinna med uppsatt hår som ser ut som gamla stereohörlurar över öronen. Hon är en av hjältarna i rebellalliansen och är en självmedveten kvinna som kan vara ganska dryg mot dem som inte visar henne tillräcklig respekt. Klär sig enfärgat, och inga pastellfärger. Favoritfärger: brunt och ljusbrunt. Leia vill ha chans på Han Solo som hon gärna pratar med nØllan om.",
    "props": "Ett saftigt rött läppstift. Fint ska det va’!",
    "missions": [
        {
            "id": "leia:0",
            "comment": "Den nØllan som tar sig in i cellen får en puss på kinden med RIKLIGT med läppstift, denna puss fungerar senare som bevis för att uppdraget är slutfört. När du har blivit räddad ska du med ett glädjetjut be nØllan att ta sig till rebellbasen och visa upp pussmärket så att rebellerna vet att du är friad!",
            "response": "“Här ska du få ett bevis på att du befriat mig, skynda nu till rebellbasen med det!”"
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/leias_vakter.json
{
    "id": "leias_vakter",
    "name": "Leias vakter",
    "location": "Se översiktsdokument på Drive",
    "area": "Cell 2187, Detention Block AA-23 - Borderland Regions",
    "persona": "Tvättäkta stormtroopers inklusive vapen och en ondsint attityd. Skräm gärna nØllan som springer omkring i D-huset (även om de inte är på väg till Leia) genom att stirra ut dem, smyga på dem eller följa efter dem. Men ni måste vakta dörren till Leia om någon nØllan är på väg dit. Det ligger lite kålhuvuden i närheten för ett annat uppdrag, se till att ni vet var de ligger och se till att nØllan bara tar ett per grupp -> Dessa vakter kommer att byta av med Stormtroopers lite då och då. Läs därför Stormtroopers beskrivning också! <-",
    "props": "Ett ständigt fulladdat vattengevär (som INTE får användas inomhus!).",
    "missions": [
        {
            "id": "leia:0",
            "comment": "När nØllan kommer och vill bli insläppta så nekar ni dem för att de inte är stormtroopers. Bredvid Leias cell ligger stormtroopernas omklädningsrum. Om nØllan inte fattar att de ska gå dit och klä ut sig så försök att hinta på något smart sätt. Släpp bara in dem om en nØllan har klätt ut sig, men fråga vilka de andra är så de måste hitta på något i stil med att de andra är fångar. Ni kan ju föreslå det om nØllan verkar förvirrad, det är roligare om alla får gå in i cellen!",
            "response": "För att neka: “Våra order är att bara släppa in stormtroopers, gå härifrån.”, efter att någon klätt ut sig, indikera ej utklädda nØllan: “Är det där de nya fångarna?” "
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/obi-wan.json
{
    "id": "obi-wan",
    "name": "Obi-Wan Kenobi",
    "location": "META",
    "area": "Mos Eisley",
    "persona": "Lång, klok gammal man. Klär sig i ökenfärgad kåpa. Gärna vitt hår och skägg. Obi Wan ska ligga ganska lågt i baren när nØllan är där. Han ska vara hemlig och nØllan måste leta upp honom. Önska nØllan lycka till och upprepa “må kraften vara med dig”. Det finns ett annat uppdrag som involverar lasersvärd (lasersvärdskuponger för att vara mer exakt), de ska prata med Big Bunji för att få rabattkuponger, inte dig.",
    "props": "En ljussabel.",
    "missions": [
        {
            "id": "jeditraning:1",
            "comment": "nØllan kommer och vill lära sin om Jedi träning/Yoda. Du ska vara tveksam att dela med information tills du blir mutad eller frågad flera gånger",
            "response": "Roboten R2D2 är en duktig navigatör och känner säkert till rymdkoordinaterna till Yodas hemplanet Dagobah. Fråga R2D2 om koordinaterna till ”Dagobah”, han sågs senast i tillsammans med ett par Jawas på Tatooine. Må kraften vara med er!"
        },
        {
            "id": "smuggelgods:1",
            "comment": "Om nØllan frågar efter smuggelgods så vill du inte ge dig det innan du fått tag i imperiets guldtackor som finns mellan Roche asteroidbälte och Corellia system.",
            "response": "Jag tog paketet i tron om att det var imperiets guldtackor, men jag hade fel. Ni måste ta hit guldtackorna innan jag ger er någonting! Jag skulle leta på mellan Roche asteroidbälte och Corellia system"
        },
        {
            "id": "smuggelgods:3",
            "comment": "När nØllan kommer tillbaka med en guldtacka (sten målad guld) säger du att du gav smuggelgodset till de gulliga Ewoksen vid Forest Moon of Endor då du inte kunde motstå dem.",
            "response": "Ge hit guldtackorna, de är inte för nybörjare!.... Tyvärr har jag alltid varit svag för Ewoker. De kom och ville ha godset, och medan deras lurviga päls förtrollade mig, så lyckades de ta det ifrån mig. Det ryktas om att Ewokerna håller hus på sin hemplanet, Endors skogsmåne."
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/rebelledare.json
{
    "id": "rebelledare",
    "name": "Rebelledare",
    "location": "Flygande",
    "area": "Flygande",
    "persona": "Du hjälper nØllan med allt de behöver och håller dig uppdaterad mot rebellbasen. Spring gärna runt på borggården samt E och D-husen, där fastnar många.",
    "props": "Massa krediter. Telefon och dator är ett måste, gärna ett coolt headset också.",
    "missions": [],
    "events": []
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/CptAntilles.json
{
    "id": "CptAntilles",
    "name": "Captain Antilles",
    "location": "",
    "area": "Rebellbasen",
    "persona": "Antilles är en Kapten i rebellernas flotta och har nu fått det ärofyllda uppdraget att vakta rebellbasen",
    "props": "Wireless lurar helst kopplat till HQ för att titel ska kunna säga åt Antilles att släppa in folk ",
    "missions": [
    ],
    "events": [
    ]
}
