=== datasektionen/hurryscurry/resources/rpu/schemas/schema.characters.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {},
    "id": "characters-schema",
    "properties": {
        "area": {
            "id": "/properties/area",
            "type": "string"
        },
        "events": {
            "id": "/properties/events",
            "items": {
                "additionalProperties": false,
                "id": "/properties/events/items",
                "properties": {
                    "comment": {
                        "id": "/properties/events/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/events/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/events/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "id": "/properties/id",
            "type": "string"
        },
        "location": {
            "id": "/properties/location",
            "type": "string"
        },
        "missions": {
            "id": "/properties/missions",
            "items": {
                "additionalProperties": false,
                "id": "/properties/missions/items",
                "properties": {
                    "comment": {
                        "id": "/properties/missions/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/missions/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/missions/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "persona": {
            "id": "/properties/persona",
            "type": "string"
        },
        "props": {
            "id": "/properties/props",
            "type": "string"
        }
    },
    "required": [
        "persona",
        "name",
        "area",
        "events",
        "location",
        "props",
        "id",
        "missions"
    ],
    "type": "object"
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/rebellagent.json
{
    "id": "rebellagenten",
    "name": "Rebellagenten",
    "location": "Meta",
    "area": "Mos Eisley",
    "persona": "Du hjälper nØllan med allt de behöver och håller dig uppdaterad mot rebellbasen. Du har en rebellbasklient igång och kan tilldela grupper events. Om någon grupp ligger riktigt, riktigt illa till kan du erbjuda dem att lösa ett pussel/en gåta för immideate cash.",
    "props": "Massa krediter, ett pussel. Telefon och dator är ett måste, gärna ett coolt headset också.",
    "missions": [
        {
            "id": "luke:2",
            "comment": "Den här ledtråden ges av rebellagenten i Mos Eisley. nØllan ska anteckna sektornumret och fortsätta leta efter R2D2.",
            "response": "Jag ser att Luke sitter fast i ett skräpshakt i sektor GE2130! R2D2 kan hjälpa er rädda Luke, jag såg honom senast i baren."
            
        },
        {
            
            "id": "wmd:2",
            "comment": "Den här ledtråden ger rebellagenten i Mos Eisley muntligen om någon frågar efter »adressen till Mordor».",
            "response": "Gallandro håller till runt Roche Asteroidbälte och kanske kan sälja er en puffra, eller något mer effektivt än så…"
        }

    ],
    "events": []
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/yoda.json
{
    "id": "yoda",
    "name": "Yoda",
    "location": "Dagobah / Maz Kanatas Wärdshus (E35)",
    "area": "Borderland Regions",
    "persona": "Som en grön nyfödd skrynklig mupp i brun kappa. Plira på nØllan, försök sno saker av den och gnäll oerhört om de klagar. Pratar alltid med taskig grammatik och häver ur sig det ena obegripliga visdomsordet efter det andra (kolla bibeln för exempel).",
    "props": "39 AA batterier (3 st per nollegrupp), pingisboll som det står “bomb” på.",
    "missions": [
        {
            "id": "jeditraning:0",
            "comment": "Om nØllan ger dig 1200 krediter (och kanske något ätbart - inte nödvändigt) så kan träningen börja! En i gruppen tar på sig en hjälm som man inte ser igenom och får en pingisboll i handen som det står “bomb” på. Nu ska resten av gruppen guida personen genom en labyrint byggd av bord med hjälp av kraften, så att bomben kan släppas ner i en tratt i slutet av labyrinten. När nØllan är klar får de KRAFTEN i form av två batterier till ljussabeln (plastsvärdet).",
            "response": "Pratar för all del med den taskigaste grammatik du kan, så länge nØllan förstår"
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/deppo.json
{
    "id": "deppo",
    "name": "Deppo",
    "location": "Engelska parken-ish",
    "area": "Junkfort Station - Nar Shaddaa",
    "persona": "Deppo är en mekaniker som går klädd i blåställ och gärna har lite skiftnycklar och skruvmejslar i fickor och händer. Oljig i ansiktet och kan prata i timmar om en förgasare. Deppo får höra en del från folk som kommer in med sina skepp för reparation och har därför ganska bra koll på vad som händer under radarn i cyberspace.",
    "props": "Silvertejp/eltejp, 12 st bokmärken (gärna söta änglar), 12 st plåster och 12 st 3CPO huvuden.",
    "missions": [
        {
            "id": "1000arsservice:2",
            "comment": "Om nØllan ber att du ska utföra 1000-årsservice på falken skickar du dem vidare till R2D2 i Mos Eisley på jakt efter en »hyperdrive motivator». När nØllan återvänder med ett autentiskt pappersplan med sig så gör du en 1000-års service på Falken för 1000 krediter, signerar flygplanet och bockar av dess kod på listan du fått (IOP235667980, PLAN7146387, VIGG2988756, NO123495MN, FR0GG298347, SLAV12457690, GOOG2203452, KLÄG253401G, GMHRL249D14, NLS50106Q40, TJOS0256KFD, JAS1337FLYG).",
            "response": "”Det enda som behövs är en ny »hyperdrive motivator». Skaffa en åt mig så kan jag laga ert skepp R2D2 vet förmodligen var ni kan få tag på en. Sist jag såg R2D2 var han i baren i Mos Eisley.”"
        },
        {
            "id": "c3po:1",
            "comment": "Om nØllan frågar om C3PO, ta upp C3POs huvud och sitt med det i knät. Berätta för nØllan hur några jawas kommit och stulit C3PO’s resterande tre reservdelar då han skulle repareras. Be nØllan att hämta tillbaka delarna till dig så att du kan montera ihop C3PO igen. Säg att jawas är ganska läskiga varelser som brukar hålla till på ökenplaneten Tatooine.",
            "response": ""
        }, {
            "id": "c3po:3",
            "comment": "När nØllan kommer tillbaka med C3POs delar, tackar du nØllan och sätter du ihop de med lite silvertejp och ger den hela roboten till nØllan. nØllan ska sedan ta med sig C3PO till rebellbasen för att redovisa uppdraget.",
            "response": ""
        }, {
            "id": "solo:1",
            "comment": "Om nØllan frågar dig om Han Solo hjälper du dem med lite information kring Solos fångenskap och att en hemlig kod behövs för att nå hans cell. Sen skickar du dem vidare till hålet i Wild Space och Luke som var med på Han Solos svensexa. Se response för ordagran replik.",
            "response": "“Jag vet inte var Han Solo hålls fången, men jag har hört rykten om att det krävs en hemlig kod för att komma in i cellen. Om ni hittar koden kanske ni även kommer över cellens position. Leta reda på Luke, och fråga honom om han vet mer om koden och var Han Solo är fångad. Ni hittar honom i hålet vid Wild Space.“"
        }
    ],
    "events": [
        {
            "id": "negative:1",
            "comment": "Efter ett misslyckat hopp i hyperrymden hamnar nØllan i ett asteroidbälte. Vid en hård kollision med en av asteroiderna böjdes nØllans parabol till och nØllan får numera bara in FTV. För minst 500 krediter lagar du skeppet. Beviset utgörs av den bit silvertejp du sätter runt fingret på en av nØllan.",
            "response" : ""
        },
        {
            "id": "negative:4",
            "comment": "Förste skytten på nØllans skepp har fastnat med tandställningen i slutstycket på laserkanonen. Du har god hand med skiftnycklar och en tandläkarutbildning i bakfickan. För 300 krediter räddar du nØllan ur den pinsamma situationen och ger dem ett bokmärke som belöning (bevis).",
            "response" : ""
        },
        {
            "id": "negative:8",
            "comment": " nØllan har sumobrottats med Jabba the Hut (ett stort misstag). Deppo vet även hur man lagar trasiga nØllan. För 200 krediter lagar du nØllan genom att sätta ett plåster i pannan på den skadade (bevis).",
            "response" : ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/maz_kanata.json
{
    "id": "maz_kanata",
    "name": "Maz Kanata",
    "location": "Maz Kanatas Wärdhus / Dagobah (E32)",
    "area": "Borderland Regions",
    "persona": "En orange liten skrynklig sak med jättestora glasögon. Slitna kläder i naturliga färger och ett stort leende. Hård mot Yoda som är i samma rum dock, speciellt när Yoda drygar sig mot nØllan (tar absolut ingen skit från honom). Spela dock gärna lite ledsen när du tänker på din älskade Chewie (vilket borde hända ofta i alla konversationer).",
    "props": "En högtalare.",
    "missions": [
        {
            "id": "stridsteknik:1",
            "comment": "nØllan vill att du ska lära dem en ny stridsteknik som är effektiv mot stormtroopers. Du lär dem ingenting förrän du fått se din älskade Chewbacca i karaokebaren (D2) i Corellia System.",
            "response": "“Jag lär er ingenting förrän jag får en autografbild av min älskade Chewbacca igen. Senaste gången jag såg honom var han i kareokebaren i Corellia System.“"
        },
        {
            "id": "stridsteknik:3",
            "comment": "nØllan har nu fixat en snygg och sexig autografbild av Chewbacca. Du lär nu ut den nya stridstekniken som är flossing (Backpack kid) som körs till Swish Swish (låten då alltså). Du säger även till dem att de bör prova den på en stormtrooper och ta en bild som bevis.  Glöm inte att påpeka att stridsteknikens styrka växer exponetiellt med hur många som utövar den.",
            "response": ""
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/cpt_antilles.json
{
    "id": "cpt_antilles",
    "name": "Captain Antilles",
    "location": "Se översiktsdokument på Drive",
    "area": "Rebellbasen",
    "persona": "Antilles är en Kapten i rebellernas flotta och har nu fått det ärofyllda uppdraget att vakta rebellbasen. När nØllan kommer se till att det bara är en nØllegrupp i rebelbasen samtidigt och att titel är redo att ta emot nØllan",
    "props": "Wireless lurar helst kopplat till HQ för att kunna komunicera med titel",
    "missions": [],
    "events": []
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/latara.json
{
    "id": "latara",
    "name": "Latara",
    "location": "Norra delen av E i en korridor",
    "area": "Cloud City",
    "persona": "Latara är en kvinnlig rymdfåne som tycker om att prata skit och ljuga. Hon är en Ewok, och som alla sådana ser hon ut som en teddybjörn. Latara spelar flöjt så fort hon får chansen. Prata gärna som en ewok, dvs pipig och grinig. Latara ska argumentera och pruta när det gäller pengar, samt vara lite hetsig när hon berättar att hon har blivit bestulen!",
    "props": "Kattmat, en flöjt, ca 7000 krediter. ",
    "missions": [
        {
            "id": "ritningar:1",
            "comment": "När nØllan kommer till dig och frågar om ritningarna till Dödsstjärnan blir du upprörd och berättar att det var någon skum typ som stal dom av dig! Gallandro vet kanske någonting om saken, senaste gången du såg honom smög han runt i Roche Asteroidbälte.",
            "response": "“Det var någon skum typ som stal dom av mig! Gallandro vet kanske någonting om saken, senaste gången jag såg honom smög han runt i Roche Asteroidbälte.”"
        },
        {
            "id": "dodsstjarnan:3",
            "comment": "Om nØllan frågar efter koordinaterna till Dödsstjärnan förhandlar du så de betalar 100 krediter, sen berättar du dramatiskt att dödstjärnan finns vid solsystemet Endor.",
            "response": "“Dödsstjärnan kan skådas som något stort, mörkt och runt i solsystemet Endor.”"
        }
    ],
    "events": [
      {
          "id": "negative:3",
          "comment": "nØllan vill köpa hundmat. De får då köpa en Frolic-bit (fast kattmat) för ca 100 kred. Tjafsa gärna om priset men ta inte för mycket (inte mer än 300 kred).",
          "response" : ""
      },
      {
          "id": "positive:5",
          "comment": "nØllan ska berätta en rolig historia som innehåller orden 'tomat' och 'går vi'. Beroende på hur roliga och fantasifulla nØllan är belönar du dem med ett asgarv och 200-500 kred. Signera sedan deras händelsekort.",
          "response" : ""
      },
      {
          "id": "positive:7",
          "comment": "nØllan kommer och kräver pengarna tillbaka på en hudkräm som du har sålt dem. Efter lite tjafs och tjat ger du dem 200 kred och signerar händelsekortet.",
          "response" : ""
      }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/luke.json
{
    "id": "luke",
    "name": "Luke",
    "location": "Se översiktsdokument på Drive",
    "area": "Wild Space",
    "persona": "Luke Skywalker är en nyfiken och härlig kille som för det mesta leker jediriddare. Han är oftast glad och trevlig. Dock verkar han sitta fast med en orm runt benet djupt i något som skulle kunna vara ett sopprum fullt av vatten, men han håller humöret uppe ändå!",
    "props": "Inplastade lappar med bokstäver som bildar “Jungfru Maria”, en gosedjursorm att ha runt benet och en telefon nära till hands, 12 stycken tack-kort. ",
    "missions": [
        {
            "id": "solo:2",
            "comment": "När nØllan kommer förbi och frågar om svensexan känner du nostalgi kring den, men känner dig lite väl ledsen över att Han är borta för att kunna den där koden som nØllan vill ha till Han Solos fängelse. När nØllan ger dig en tillräckligt bra komplimang skiner du upp ger ut koden 750 samt att Boba Fett i Wild Space vet mer. Se response för ordagran replik.",
            "response": "“Åhhh svensexan, den var trevlig den. Det var då jag Bobba Fett, Jarjar Binks, Joe Biden och Han Solo avnjöt en romantisk trapetskväll under stjärnorna. Vi drack champagne, åt jordgubbar och fiskade fiskdamm på McSpace. Det var en fin dag, en mörk dag, det var den, eller vänta? Varför berättar jag detta? Jag känner mig plötsligt väldigt ledsen. Ryktena är sanna, Han (Solo) sitter inlåst i en cell skyddad med hemlig kod. Jag har dock hittat koden. Men hur ska jag kunna komma ihåg den när jag är så här ledsen? Om jag ska kunna minnas denna viktiga kod behöver jag nog uppmuntras lite. OOH Jo juste 750!. Boba fett minns kanske mer från den kvällen och kan berätta var Han försvann. Ni hittar honom i Wild Space. KOM IHÅG KODEN!!“"
        },
        {
            "id": "luke:1",
            "comment": "När nØllan kommer för att rädda dig undan ditt hemska öde (du sitter ju faktiskt fast i en soprumspress) är du väldigt tacksam.",
            "response": "Schysst att ni vill hjälpa mig! Jag verkar ha fastnat.. Bara R2D2 kan rädda mig från att dö i den här hålet. Han stänga av väggarna som rör sig mot mig om han vet vilken sektor jag är i! Ta er till hjälpcentret i Mos Eisley och be rebellagenten kolla upp sektornumret på deras övervakningskameror!"
        },
        {
            "id": "luke:0",
            "comment": "När nØllan kommer tillbaka efter att du har fått ett sms från R2D2 vakten att pressen har stoppats så är du superglad och säger att du är evigt tacksam. Sen som bevis för din tacksamhet ger du nØllan ett tack-kort. Sedan ska de ta med tack-kortet till rebellbasen för att visa att du är oskadd.",
            "response": ""
        },
        {
            "id": "leia:2",
            "comment": "När nØllan frågar om Leia berättar du att Leia lyckades lämna lite information hos R2D2, som de kan få ut om de löser koden. Du räcker fram lappar med bokstäver som nØllan ska lägga i en ordning som bildar lösenordet “Jungfru Maria”. När nØllan har knäckt koden skickar du dem vidare till R2D2 som senast sågs i Mos Eisley.",
            "response": "“Koden är 'JUNGFRU MARIA'! Ta er till R2D2, han kan hjälpa er! Senast sågs han i Mos Eisley!“"
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/ewok.json
{
    "id": "ewok",
    "name": "Ewok",
    "location": "Forest Moon of Endor",
    "area": "",
    "persona": "Ewoks låter och ser ut som en liten teddybjörn som har växt upp i skogen. Ewokerna talar ett pipigt och lite grinigt språk som bara C3PO kan tolka. För att nØllan ska förstå det du säger kan det vara en ide att tala pipig svenska... Ewokerna har koden som nØllan behöver för att stänga av Dödsstjärnans kraftfält.",
    "props": "En oändlig mängd nallebjörnar, en mobil, 1 ljudfil med ewok-pip, 1 ljudfil med nallegåtan, fler ewoker! Shampoo/balsam/handkräm eller liknande i en igentejpad påse (13st).",
    "missions": [
        {
            "id": "smuggelgods:0",
            "comment": "Om nØllan kommer och frågar om smuggelgods så förklara att “mysighet” uppskattas och att alla nØllan som är bekväma med det ska krama samtliga Ewoks i rummet innan de får smuggelgodset, vilket kommer vara en lypsyl i en påse.",
            "response": ""
        },
        {
            "id": "kraftfalt:0",
            "comment": "Om nØllan kommer och frågar om kraftfältet, så sätter du igång ljudfilen med Ewok-pip om de inte har C3PO framme. När nØllan tar fram C3PO så tillber du guden C3P0 och sedan sätter du igång den andra ljudfilen som är i klarspråk. Filen kommer att rada upp en viss ordning som nallebjörnarna i salen ska ligga i. Nallebjörnarna har nämligen nummer på huvudet. Dessa nummer bildar koden nØllan vill ha! Koden är 12221550 (Dubbelkolla med nallebjörnarna så att koden stämmer). Om nØllan inte fattar nånting så kan du hinta om att de kanske behöver en tolk.",
            "response": ""
        }
    ],
    "events": [
    ]
}
