=== datasektionen/hurryscurry/resources/rpu/schemas/schema.characters.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {},
    "id": "characters-schema",
    "properties": {
        "area": {
            "id": "/properties/area",
            "type": "string"
        },
        "events": {
            "id": "/properties/events",
            "items": {
                "additionalProperties": false,
                "id": "/properties/events/items",
                "properties": {
                    "comment": {
                        "id": "/properties/events/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/events/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/events/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "id": "/properties/id",
            "type": "string"
        },
        "location": {
            "id": "/properties/location",
            "type": "string"
        },
        "missions": {
            "id": "/properties/missions",
            "items": {
                "additionalProperties": false,
                "id": "/properties/missions/items",
                "properties": {
                    "comment": {
                        "id": "/properties/missions/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/missions/items/properties/id",
                        "type": "string"
                    },
                    "response": {
                        "id": "/properties/missions/items/properties/response",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "id",
                    "response"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "persona": {
            "id": "/properties/persona",
            "type": "string"
        },
        "props": {
            "id": "/properties/props",
            "type": "string"
        }
    },
    "required": [
        "persona",
        "name",
        "area",
        "events",
        "location",
        "props",
        "id",
        "missions"
    ],
    "type": "object"
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/darthvader.json
{
    "id": "darthvader",
    "name": "Darth Vader",
    "location": "Millespottan",
    "area": "The Final Battlefield",
    "persona": "Historiens minst faderliga faderfigur. Idag är du här för att ta över KTH. Du slåss tappert men blir besegrad av det vinnande laget. Sök upp RPU för mer information om hur det stora slaget går till",
    "props": "Klassisk mundering med mask, cape, lasersvärd.",
    "missions": [],
    "events": []
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/brasck.json
{
    "id": "brasck",
    "name": "Brasck",
    "location": "Se översiktsdokument på Drive",
    "area": "Corellia System",
    "persona": "Brasck är en kryddsmugglare som sitter vid samma bord som Chief Muskov och spelar kort. Synka klädseln så att den är någorlunda likadan som Chief Muskov, Brasck bär dock alltid hatt. Brasck är opålitlig och egoistisk.\nnØllan kommer vid flera tillfällen vara tvungen att lista ut vem som är Brasck och vem som är Chief Muskov. De får då ställa ja- och nej-frågor till herrarna. Brasck ljuger alltid. Muskov talar alltid sanning. Belöna gärna nØllan (t.ex. med lite extra krediter för kryddorna) som klarar att avslöja identiteterna med endast en fråga (som inte är dum nog att fråga t.ex. “Om jag frågade dig om du är Brasck, vad skulle du svara då?“).",
    "props": "Ca 12000 krediter och en kortlek som du och Chief Muskov kan spela med. ",
    "missions": [
        {
            "id": "kryddor:0",
            "comment": "Om nØllan ger dig kryddor betalar du dem med 1200 kred och signerar deras uppdragskort.",
            "response": ""
        },
        {
            "id": "kesselrun:0",
            "comment": "Denna händelse hör till Chief Muskov, men du bör känna till dem: Om nØllan ger dig nyckeln till falken ger du tillbaka den till dem och säger att deras nästa ledtråd finns på en skylt i Endor.",
            "response": ""
        }
    ],
    "events": [
        {
            "id": "negative:5",
            "comment": "Denna händelse hör till Chief Muskov, men du bör känna till dem: Om nØllan försöker muta dig för att slippa sina böter tar du bara pengarna och flinar. Gör klart för nØllan att de har gett pengar till fel person.",
            "response" : ""
        },
        {
            "id": "positive:1",
            "comment": "Denna händelse hör till Chief Muskov, men du bör känna till dem: Om nØllan berättar att de har sett Xim the Despot säger du bara att det skiter väl du i.",
            "response" : ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/jawa.json
{
    "id": "jawa",
    "name": "Jawa",
    "location": "Se översiktsdokument på Drive",
    "area": "Tatooine - Corellia System",
    "persona": "Jawas är sandfolk som är kända för att bedra andra i sin omgivning. De är ohederliga varelser som livnär sig på att stjäla/lägga vantarna på robotar och teknik som de sedan kan sälja.\nEn jawa är till utseendet kort och klädd i en brun rock med en huva som kastar skuggor över ansiktet. Hemlighetsfull och svårtydig. ",
    "props": "C3PO-delar (12 set), eltejp/silvertejp, 3 hinkar, havregrynsgröt, lingonsylt, ett paket med flingor, några kannor med vatten och ett eller flera paket med ägg. Papper behövs också, samt 3 ögonbindlar och lock av något slag till hinkarna. Dessutom engåndshandskar för corona-safety",
    "missions": [
        {
            "id": "r2d2:2",
            "comment": "När nØllan kommer och frågar om R2D2 (kommer hända 12 ggr) så hänvisar du dem till din buddy Albeback som tagit ut R2D2 för att säljas i norra Corellia System",
            "response": "“Här i trakterna finns det inte så många köpare, så vi lät vår vän Albeback ta robotarna norrut, han bör inte hunnit ut ur Corelia System än...”"
        },
        {
            "id": "c3po:2",
            "comment": "nØllan kommer och letar efter C3PO. När de kommer till dig ska de utsättas för 3 prövningar för att få tag på alla delar som hör till C3PO, eftersom att du är uttråkad och vill ha något roligt att titta på. Innan Hurry Scurry börjar ska det därför fixas i ordning 3 hinkar. I varje hink läggs 12 st av en sorts C3PO-del i botten av hinken, sen fylls den med icky stuff. Glöm inte att täcka för hinkarna så att nØllan inte ser vad som finns i! nØllans prövning består då av: Ta fram 3 nØllan som ska få hjälpa dig att hitta C3PO, sätt på de ögonbindlar och ställ de andra i gruppen bakom hinkarna. Instruera dem att de ska ta upp endast en C3PO del. Hink nr 1 är full med havregrynsgröt, i botten på den ligger C3POs arm. Du glömde nog armen där när du åt frukost och den serverade som sked. Hink nr 2 är full av lingonsylt blandat med vatten och flingor. Där ligger C3POs kropp som du trodde att du hade lagt i ett oljebad. Ooops. Hink nr 3 är full med råa ägg. Där i finns C3POs ben som började se så dammigt ut och behövde få tillbaka lite av sin fina gula färg. Ha några kannor med vatten och lite papper när till hands så att både du och nØllan kan torka av sig.",
            "response": ""
        },
        {
            "id": "kryddor:1",
            "comment": "nØllan kommer till dig för att hjälpa dig att genomföra ett uppdrag som kryddsmugglare. Du är hemlighetsfull och viker bort blicken när de kommer fram, sen säger du att de som första uppdrag ska ta sig till baren i Mos Eisley och viska den överenskomna koden »Chubb Scutt skickade mig»",
            "response": ""
        },
        {
            "id": "kryddor:3",
            "comment": "När nØllan kommer tillbaka med kryddor (en tepåse) säger du att de ska bege sig till ljusgården i Corellia System för avlämning.",
            "response": "“Bege er till ljusgården i Corellia System för avlämning. Ryktet säger att platsen utmärkts med lysande bokstäver...”"
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/chief_muskov.json
{
    "id": "chief_muskov",
    "name": "Chief Muskov",
    "location": "Ljusgården i D",
    "area": "Corellia System",
    "persona": "Muskov är intergalaktisk polis som ständigt är på spaning efter kryddsmugglare. Han ska se ut och agera som en typisk rymdpolis när han sitter och spelar kort med Brasck.\nnØllan kommer vid flera tillfällen vara tvungen att lista ut vem som är Brasck och vem som är Chief Muskov. De får då ställa ja- och nej-frågor till herrarna. Brasck ljuger alltid. Muskov talar alltid sanning. Belöna gärna nØllan (t.ex. med lite extra krediter för kryddorna) som klarar att avslöja identiteterna med endast en fråga (som inte är dum nog att fråga t.ex. “Om jag frågade dig om du är Chief Muskov, vad skulle du svara då?“).",
    "props": "Ca 1000 kred, penna att signera händelsekort med och en kortlek. ",
    "missions": [
        {
            "id": "kryddor:0",
            "comment": "nØllan kommer för att sälja kryddorna till Brasck. Om nØllan ger dig kryddor beslagtar du dem och skäller ut dem efter noter. Gör klart för dem att de har gett kryddorna till fel person och misslyckats med uppdraget, och får börja om genom att hämta en ny kryddpåse. ",
            "response": ""
        }
    ],
    "events": [
        {
            "id": "negative:5",
            "comment": "Om nØllan försöker muta dig för att slippa sina böter förhandlar du med dem. Ett skäligt pris är ca 500 kred. När ni har kommit överens säger du: “ja, då river vi den här då” och river deras händelsekort (hahaha det kunde de ha gjort själva).",
            "response" : ""
        },
        {
            "id": "positive:1",
            "comment": "Om nØllan berättar att de har sett Xim the Despot tackar du för upplysningen, ger nØllan 200 kred och signerar händelsekortet.",
            "response" : ""
        }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/gallandro.json
{
    "id": "gallandro",
    "name": "Gallandro",
    "location": "Roche Asteroidbälte",
    "area": "",
    "persona": "Cool person, handelsresande, skum och egen företagare. Trenchcoat och hatt eller nåt sånt. Om glasögon så attans coola sådana. Gatuförsäljarstilen, öppna rocken och visa dina varor!",
    "props": "13 ritningar på massförstörelsevapen/WMD/diskett, 13 påsar med schampo (små testexemplar liksom...), ca 2500 krediter och en penna att signera kort med. Sen skadar det inte om Gallandro har med sig alla möjliga nödvändiga och onödiga saker utöver de här, han är ju trots allt en “Go-to-guy”!",
    "missions": [
        {
            "id": "wmd:3",
            "comment": "När nØllan kommer och frågar om en ritning för ett massförstörelsevapen verkar du först lite besvärad, men sen säljer du en ritning(diskett) till nØllan för ca 1000 krediter. Förhandla gärna men håll dig inom intervallet 800-1200. Berätta sedan för nØllan att de *måste* få den godkänd av Imperiets Ministerie för Inspektion och Övrig Hantering av Massförstörelsevapen och Laserbazookas i Cloud City.",
            "response": ""
        },
        {
            "id": "ritningar:2",
            "comment": "nØllan kommer att fråga dig om ritningarna till Dödsstjärnan. Du vet ingenting förrän du fått lite pengar (ca 300 krediter, förhandla!). Sen seger du att någon i Mos Eisley ska ha ritningarna, samt att de måste godkännas av Imperiets Ministerie för Inspektion och Övrig Hantering av Massförstörelsevapen och Laserbazookas i Cloud City.",
            "response": "“Det ryktas om att en en skum typ som brukar hänga i Mos Eisley har ritningarna i sin ägo. Om detta rykte skulle visa sig vara sant, så måste ni får ritningarna godkända Imperiets Ministerie för Inspektion och Övrig Hantering av Massförstörelsevapen och Laserbazookas i Cloud City”"
        }
    ],
    "events": [
      {
          "id": "negative:2",
          "comment": "nØllan är i stort behov av mjällschampo. Sälj en liten påse med schampo till nØllan för ca 100 krediter.",
          "response" : ""
      },
      {
          "id": "positive:6",
          "comment": "Space'r'Us: nØllan har vunnit en slogantävling med bidraget “Om det ryms i rymden så säljer vi det” till hårdvarujätten Space'r'Us. Kolla att de har korrekt händelsekort och betala dem 400 kred. Signera sedan kortet.",
          "response" : ""
      }
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/han_solo-vakt.json
{
    "id": "han_solo-vakt",
    "name": "Han Solo-vakt",
    "location": "D3",
    "area": "Cryo-chamber 5 / Ice-bar - Corellia System",
    "persona": "Den som vaktar Han Solo är anställd av Jabba the Hut. Eftersom alla Jabbas polare och vänner är mutanter, slemmiga och missbildade så är det just så du ser ut. Så läbbig och konstig som möjligt. Flåsa och var äcklig.",
    "props": "Gärna något som ser ut som ett vapen! Sjukvårdskit och fylld vattenflaska, förhöjd risk för skrapsår pga podracing. Hoverboard och sparkcykel för podracing",
    "missions": [
        {
            "id": "solo:0",
            "comment": " När nØllan kommer fråga efter koden (750). Dock är ni givetvis öppen för mutor, särskilt i form av mat, och kan då tänka er att avslöja enstaka siffror i koden. När de gett dig rätt kod klagar en av er på att det är långtråkigt att vakta den nedfrysta Han Solo så nØllan måste tävla mot dig i din favoritsport podracing. Den som ska race:a tar med nØllan ut till banan på parkeringen utanför D (gå via utgången vid Örådet). Sen är det dags för podracing! När ni race:at färdigt släpper ni in nØllan i Cryo-chamber. Se till att de bara tar ett av isblocken och kolla att samma grupp inte kommer mer än en gång. Säg också att de inte får ut pappret i isblocket med våld, utan smälter blocket i ett handfat.",
            "response": "För all del, kom på något witty med att det är stentråkigt att vakta någon som är nedfryst."
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/administrator.json
{
    "id": "administrator",
    "name": "Imperiets administratör",
    "location": "Högst upp i E-husets norra del",
    "area": "Högst upp i Cloud City",
    "persona": "Administratör, lämpligen av den mycket strikta sorten. Det enda som är viktigt är papper. Utan dig slutar imperiet att fungera. Gör det klart för nØllan att du är en mycket viktig och högt uppsatt person. De papper som du skriver är grunden som imperiet står på. Allt måste skötas enligt regelboken. Administratören är rätt så dryg och kan till exempel be nØllan ställa upp sig på led sorterade exempelvis efter mellannamn medan de väntar på en underskrift. ",
    "props": "Penna och “Ansökan om order av Inspektion-papper”. Lämpligtvis 28 kopior (alltså 28*2 papper). Byråkratiska papper kan hittas på driven.",
    "missions": [
        {
            "id": "ritningar:0",
            "comment": "När nØllan kommer till Cloud City söker de upp Administratören. Han ger dem “Ansökan om order av Inspektion” där båda kopiorna (Administratörens & ansökarens) ska fyllas i osv. Administratören behåller den ena kopian. Administratören fyller i den och stämplar den och skickar nØllan till Inspektören. Om Inspektören finner ansökan giltig stämplar han den samt ber nØllan fylla i Order om Inspektion (båda kopiorna osv). Han stämplar den (på checkrutan Inspektion utförd) och skickar ner nØllan till Administratören igen, som då kryssar i rutan Objektet godkänt samt sätter än stämpel över denna ruta. Ansökan är nu godkänd och nØllan kan bege sig tillbaka till rebellbasen. *Både Inspektören och Adminstratören skall vara mycket noggranna och gärna klaga på om vissa fält inte är ifyllda.(Dra inte ut på det alltför mycket bara) Mutor tas gärna emot och om muta har givits så måste belopp fyllas i samt att en stämpel måste sättas över mutebeloppet. Antalet fält som då måste fyllas i minskar drastiskt.",
            "response": ""
        },
        {
            "id": "wmd:0",
            "comment": "Samma sak som för ritningar:0",
            "response": ""
        }
    ],
    "events": [
    ]
}

=== datasektionen/hurryscurry/resources/rpu/data/characters/r2d2-vakt.json
{
    "id": "r2d2-vakt",
    "name": "Albeback",
    "location": "Se översiktsdokument på Drive",
    "area": "Corellia System",
    "persona": "R2D2-vakten är en Jawa (talar därför inte direkt) som håller R2D2 fånge men för en summa av 200 krediter låter du nØllan motvilligt använda R2D2. Du har nämligen (motvilligt) fått lämna din hemplanet Tatooine för att sälja R2D2, därav ditt namn (“I'll be back”).\nDu ska ha kåpa så att ansiktet inte syns och gärna lysande ögon. Det vore skitcoolt om man byggde en ståltrådsställning med två röda lysdioder som man fäster innanför kåpan sen drar man fram kåpan ordentligt och ser till att rummet är mörkt så att bara dioderna syns under kåpan. (det sägs att det går och ser skithäftigt ut)\nnØllan kommer i samband med 6 st olika uppdrag vara tvungna att fråga R2D2 om råd. De kan också, när de vill, komma och fråga R2D2 om något. nØllan får bara prata med R2D2 under en kort tid. Släng ut dem när de verkar ha fått den information de behöver. Du måste undvika köbildning.\nOm R2D2 går och hänger sig så får du ta över hans roll genom att använda en utskriven lista över R2D2:s databas.",
    "props": "En pappersskylt “Köp droid så jag kan åka tillbaka till mina vänner på Tatooine”, samt en R2D2 som helst ser ut precis som den riktige. Den baseras på en dator med skärm, tangentbord och helst högtalare (laptop), beroende på vilken version av programmet som körs. Bygg in honom i en papperskorg, tunna, papp eller liknande (dvs använd läsksoptunnan i meta). Om R2D2 pajar, se till att ha hela databasen utskriven på papper. R2D2 programmet med tillhörande databas finns på Github.",
    "missions": [
        {
            "id": "luke:5",
            "comment": "När nØllan skrivit in koden “GE2130” eller “sektor GE2130” så MÅSTE du meddela Luke (sms eller Slack) att det har hänt. R2D2 kommer att säga att avfallspressen har stoppats.",
            "response": ""
        }, {
            "id" : "leia:5",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »jungfru maria». Dubell-trippelkolla att databasen skriver rätt area (sal, allstå)!",
			"response" : "Leia sitter i cell 2187, Detention Block AA-23, area E52 i södra Borderland Regions."
        }, {
            "id" : "prisjagare:4",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »joruus c'baoth».",
            "response" : "Han gömmer sig i norra Borderland Regions och har en förkärlek till färgen brun."
        }, {
            "id" : "jeditraning:4",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »dagobah».",
            "response" : "Planeten Dagobah ligger i södra Borderland Regions."
        }, {
            "id" : "1000arsservice:5",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »hyperdrive motivator».",
            "response" : "Tydligen har Chewbacca också varit på vift i stjärnrymden och letat efter en hyperdrive motivator. Men han verkar visst ha blivit distraherad av några cyber-synthar. Gå till karaokebaren i södra delen av Correlia System och hjälp honom!"
        }
    ],
    "events": [
    ]
}
