=== datasektionen/hurryscurry/resources/rpu/schemas/schema.missions.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {},
    "id": "missions-schema",
    "properties": {
        "clues": {
            "id": "/properties/clues",
            "items": {
                "additionalProperties": false,
                "id": "/properties/clues/items",
                "properties": {
                    "characters": {
                        "id": "/properties/clues/items/properties/characters",
                        "items": {},
                        "type": "array"
                    },
                    "comment": {
                        "id": "/properties/clues/items/properties/comment",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/clues/items/properties/id",
                        "type": "string"
                    },
                    "text": {
                        "id": "/properties/clues/items/properties/text",
                        "type": "string"
                    }
                },
                "required": [
                    "comment",
                    "text",
                    "id",
                    "characters"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "id": "/properties/id",
            "type": "string"
        },
        "main": {
            "additionalProperties": false,
            "id": "/properties/main",
            "properties": {
                "background": {
                    "id": "/properties/main/properties/background",
                    "type": "string"
                },
                "goal": {
                    "id": "/properties/main/properties/goal",
                    "type": "string"
                },
                "hint": {
                    "id": "/properties/main/properties/hint",
                    "type": "string"
                },
                "reward": {
                    "id": "/properties/main/properties/reward",
                    "type": "string"
                },
                "title": {
                    "id": "/properties/main/properties/title",
                    "type": "string"
                }
            },
            "required": [
                "hint",
                "reward",
                "goal",
                "background",
                "title"
            ],
            "type": "object"
        },
        "meta": {
            "additionalProperties": false,
            "id": "/properties/meta",
            "properties": {
                "props": {
                    "id": "/properties/meta/properties/props",
                    "type": "string"
                },
                "requirements": {
                    "id": "/properties/meta/properties/requirements",
                    "type": "string"
                },
                "resolution": {
                    "id": "/properties/meta/properties/resolution",
                    "type": "string"
                }
            },
            "required": [
                "requirements",
                "resolution",
                "props"
            ],
            "type": "object"
        }
    },
    "required": [
        "main",
        "meta",
        "id",
        "clues"
    ],
    "type": "object"
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/wmd.json
{
	"id" : "wmd",
	"main" : {
		"title" : "Införskaffa WMD",
		"background" : "Kriget har nu pågått tämligen rymdlänge och nØllans vapenarsenal börjar tryta. Den sista laserkatapulten gick sönder igår, till och med jonknivarna har blivit slöa och börjat rosta. Det enda vapen som återstår är gummisnoddarna. På sistone har dock Stormtroopers utvecklat rustningen Kevlar Mark III-b som är i stort sett immuna mot gummivapen. Rykten gör gällande att en ljusskygg vapenhandlare säljer ritningarna till ett nytt särdeles kraftfullt vapen som definitivt skulle ge rebellerna en större chans i slaget.",
		"goal" : "Hitta vapenhandlaren och få hen att ge er ritningarna, samt ansök om alla erfordeliga tillstånd.",
		"reward" : "nØllans belöning för detta uppdrag kommer inte att bestå av några krediter (giriga nØllan!). Ritningen till ett, inte så lite, potent vapen är belöning nog.",
		"hint" : "Kan det hända att någon har placerat ut en brevbomb vid valvet mellan Borderland Regions och Corellia System kanske..."
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "Här i Mos Eisley är allting bra! Om du söker mig så gå in i baren i Mos Eisley och fråga efter adressen till Wookieleaks. Hälsningar Gallandro, vapenhandlare.",
			"comment" : "Den här ledtråden skall skrivas på ett vykort som tejpas upp i valvet mellan E- och D-huset.",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "Gallandro håller till runt Roche Asteroidbälte och kanske kan sälja er en puffra, eller något mer effektivt än så…",
			"comment" : "Den här ledtråden ger rebellagenten i Mos Eisley muntligen om någon frågar efter »Wookieleaks».",
			"characters" : []
		},
		{
			"id" : "3",
			"text" : "nØllan har nu ritningen. Nu måste nØllan bara få den godkänd av Imperiets Ministerie för Inspektion och Övrig Hantering av Massförstörelsevapen och Laserbazookas i Cloud City.",
			"comment" : "Den här ledtråden ges av Gallandro efter att han har sålt ritningarna för 1000 krediter.",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "När nØllan kommer till Cloud City söker de upp Administratören. Han ger dem “Ansökan om order av Inspektion” där båda kopiorna (Administratörens & ansökarens) ska fyllas i. Administratören behåller den ena kopian. Administratören fyller i den och stämplar den och skickar nØllan till Inspektören. Om Inspektören finner ansökan och ritningen (en diskett) giltig, stämplar han den samt ber nØllan fylla i ”Order om Inspektion” (båda kopiorna). Han stämplar den (på checkrutan Inspektion utförd) och skickar ner nØllan till Administratören igen.  Administratören stämplar sedan åläggandet ytterligare några gånger, varpå n0llan har klarat uppdraget. Mellan varje kontakt med Administratören/Inspektören krävs en del köande och byråkrati.",
		"requirements" : "Uppdraget redovisas genom att nØllan tar med sig sin nyinköpta ritning och intyg och visar dem i rebellbasen.",
		"props" : "Den enda rekvisita som behövs är ett vykort samt 14 stycken disketter, som tillhandahålls av Gallandro. Vad det ankommer personer så behövs rebellagenten i Mos Eisley samt vapenhandlaren Gallandro (alla måste givetvis vara informerade om vad som skall sägas). Inga av dessa är dock specifika för uppdraget. Dessutom behövs Inspektören och Administratören sittandes vid bord med titelskylt (“Inspektör” respektive “Administratör”), officiella papper och mycket stämplar. Inspektören kan med fördel ha en våg som hen använder för att inspektera disketten med. “All electrons accounted for”, och även möjligen en “Administratör”-skylt (så att hen kan låtsas vara administratören för att lura nØllan)."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/prisjagare.json
{
	"id" : "prisjagare",
	"main" : {
		"title" : "Prisjägare",
		"background" : "Sedan huvudjägarna råkade åka vilse i hyperrymden finns det alltid för få prisjägare. Att mot betalning hämta in åtråvärda personer är tillräckligt lukrativt för att de flesta med kapacitet nog ska åta sig såna uppdrag.",
		"goal" : "nØllan ska skaffa sig ett kontrakt och utföra det med bravur, allt för att få den inte så speciellt dåligt tilltagna belöningen.",
		"reward" : "Belöningen består av, förutom känslan av att ha utfört ett hyggligt dagsverke, 2000 krediter.",
		"hint" : "Ni och er uppdragsgivare, Boba Fett, har bestämt träff i Wild Space."
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "Jag vill att Joruus C'baoth skall röjas ur vägen. Leverera hans huvud till min kumpan i rebellbasen. Jag har hört att R2D2 vet var han befinner sig. Namnet Joruus C'baoth kanske kan väcka robotens minne till liv. R2D2 såg jag senast i baren i Mos Eisley.",
			"comment" : "Det här ledtråden ger Boba Fett i Wild Space muntligen om nØllan frågar om prisjakt. ",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "Det var ett par jawas från Tatooine som drog förbi med ett antal robotar på släp för tre månar sedan...",
			"comment" : "Den här ledtråden ges av barpersonalen i Mos Eisley och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "3",
			"text" : "Här i trakterna finns det inte så många köpare, så vi lät vår vän Albeback ta robotarna norrut, han bör inte hunnit ut ur Correlia System än...",
			"comment" : "Den här ledtråden ges av Jawas på Tatooine och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "4",
			"text" : "Han gömmer sig i norra Borderland Regions och har en förkärlek till färgen brun.",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »joruus c'baoth».",
			"characters" : []
		},
		{
			"id" : "5",
			"text" : "Grattis nØllan! Efter en hård strid tog ni slutligen kål på Joruus C'baoth. Ta med hans huvud till rebellbasen som bevis på att ni klarat uppdraget. Det kan hända att det ligger fler huvuden här och i sådant fall skall nØllan bara ta med sig ett av dem.",
			"comment" : "Tillsammans med ledtråden ligger 14 stycken kålhuvuden.",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "nØllan tar med sig ett kålhuvud från plats 56 och beger sig mot rebellbasen.",
		"requirements" : "Uppdraget redovisas genom att nØllan lämnar in kålhuvudet i rebellbasen och inkasserar 2000 krediter.",
		"props" : "För det här uppdraget krävs 14 stycken kålhuvuden (eller 14 halva kålhuvuden) som skall symbolisera Joruus C'baoths huvud. Vidare behövs Boba Fett i Wild Space samt en fungerande R2D2 med tillhörande vakter, barpersonalen i Mos Eisley och Jawas på Tatooine. Dessa är dock ej specifika för uppdraget."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/luke.json
{
	"id" : "luke",
	"main" : {
		"title" : "Hjälp Luke",
		"background" : "Luke Skywalker har en dålig ovana att försöka rädda Rymdprinsessor och därigenom hamna i knipa. Nu har han återigen hamnat i knipa och ramlat ned i ett sopnedkast! Om det inte var nog illa att han följde med resterna av sin McStar-meny när han skulle kasta den så håller väggarna sakta men säkert på att mosa honom lika platt som Darth Vaders plånbok efter att han har köpt en påse hallon/lakrits-skallar en vanlig lördag kväll. Ni måste kvickt rädda Luke från detta hemska öde!",
		"goal" : "Ta en bild på Luke när ni har hjälpt honom undan hans hemska öde och rapportera till Rebellbasen.",
		"reward" : "nØllan kan inkassera 800 krediter efter ett väl genomfört uppdrag.",
		"hint" : "Spring till Luke och se vad han behöver hjälp med! Han verkar ha fastnat på ett djupt ställe i Wild Space."
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "“Schysst att ni vill hjälpa mig! Jag verkar ha fastnat.. Bara R2D2 kan rädda mig från att dö i den här hålet, men för att han ska kunna stänga av väggarna som rör sig mot mig måste han veta i vilken sektor jag är. Kan ni hjälpa mig att ta reda på det och berätta för R2D2? R2D2 sågs senast i baren i Mos Eisley. Dessutom börjar den här ormen gå mig lite på nerverna. Den verkar vara permanent boende här i sektorn och är ganska kärlekskrank, se om ni kan hitta en kompis till den i baren när ni ändå är i farten.“",
			"comment" : "Den här ledtråden ges av Luke när nØllan kommer dit för att hjälpa honom. ",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "Kurvig orm söker livskamrat som vill sväva fram på moln av svavel med mig! Jag bor för närvarande i ett skräpschakt på en av rymdflottans skepp i Wild Space. De senaste dagarna har jag haft en kompis över men jag börjar få en känsla av att två-beningen inte gillar mig.. Söker en ståtlig orm med livsglädjen kvar som vill åla sig fram till en samba i solnedgången. //Kramar från Tulózza, sektor GE2130",
			"comment" : "Den här ledtråden sitter i en tidning med kontaktannonser som är uppsatta i Mos Eisley. nØllan ska anteckna sektornumret och fortsätta leta efter R2D2.",
			"characters" : []
		},
		{
			"id" : "3",
			"text" : "Det var ett par jawas från Tatooine som drog förbi med ett antal robotar på släp för tre månar sedan...",
			"comment" : "Den här ledtråden ges av barpersonalen i Mos Eisley och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "4",
			"text" : "Här i trakterna finns det inte så många köpare, så vi lät vår vän Albeback ta robotarna norrut, han bör inte hunnit ut ur Correlia System än...",
			"comment" : "Den här ledtråden ges av Jawas på Tatooine och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "5",
			"text" : "Avfallspressen i sektor GE2130 har stoppats. Hälsa Luke från mig!",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »GE2130».",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "R2D2-vakten meddelar Luke att han är räddad! nØllan springer tillbaka för att se hur han mår och tar en bild på gruppen tillsammans med honom. ",
		"requirements" : "Uppdraget redovisas genom att nØllan visar upp bilden för personalen i rebellbasen där de inkasserar 800 krediter.",
		"props" : "För det här uppdraget krävs att Luke är på plats i arkitekthålet mellan Meta och Arkitekt. Utöver det behövs en kontaktannons som kan sättas upp i Mos Eisley (finns från tidigare år), ambitionsnivån på den här kan variera men har man tiden gör man bäst i att fixa något som liknar ett tidningsark med “Kontaktannonser” skrivet i stora bokstäver. Där ska det även finnas fler kontaktannonser än just den här ormens. Kanske finns det en del för rymddjur söker rymddjur? Ej specifika för uppdraget krävs även barpersonalen i Mos Eisley, Jawas på Tatooine och en fungerade R2D2 med tillhörande vakt."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/dodsstjarnan.json
{
	"id" : "dodsstjarnan",
	"main" : {
		"title" : "Förstör Dödsstjärnan",
		"background" : "Imperiet har länge slipat på sitt senaste, inte så lite farliga vapen; Dödsstjärnan. Nu står deras verk inför fullbordans rand. Inom en inte alltför lång tid kommer kejsaren ge order till sina horder att inviga detta vapen genom att bjuda en slumpmässigt vald oskyldig planet på en hejdundrande fyrverkerishow.",
		"goal" : "nØllan måste finna Dödsstjärnan och oskadliggöra denna. Eftersom nØllan nu har koden till kraftfältet borde det bli en enkel (jo, eller hur...) sak att förstöra Dödsstjärnan i triljoner bitar.",
		"reward" : "nØllans belöning kommer vara, förutom evig ära och berömmelse, en snabb placering som minst sist i Hurry Scurryn.",
		"hint" : "Det stora slaget närmar sig med stormsteg. Lyssna noga på rebellagentens instruktioner. Lycka till!"
	},
	"clues" : [],
	"meta" : {
		"resolution" : "nØllan får lines av rebellagenten och leds sedan till Millespottan för en duell med Darth Vader inför alla andra nØllan. Slår på pinata, får godis. Slut.",
		"requirements" : "Uppdraget behöver inte redovisas. nØllan har kommit minst sist!",
		"props" : "Dödsstjärnan är en piñata som nØllan slår sönder med vapnet som är ett Jesper Brännbollsträ."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/kesselrun.json
{
	"id" : "kesselrun",
	"main" : {
		"title" : "Kessel Run racet",
		"background" : "Kessel-leden är en farlig och svårnavigerad färdväg som länge har använts för att smuggla varor och andra farliga saker genom rymden. Det är även vida känt att Han Solo genomförde det ökända och extremt farliga Kessel-loppet på 12 parsecs",
		"goal" : "nØllan måste transportera farliga vapen via Kessel-leden, och säkert leverera vapnena till rebellerna",
		"reward" : "Förutom den eviga äran av att hjälpa rebellerna kan nØllan också eventuellt tjäna en hacka om de vågar vadslå några av sina krediter",
		"hint" : "Vem mer förutom Han Solo vet hur man kör Kessel-leden snabbast? Tror det finns en hårig filur som håller till i karaokebaren i Correlia System som vet. Wookies tycker förövrigt det är artigast att hälsa på sitt modersmål"
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "Åh om jag bara hade haft Han Solo och Falken så hade jag kunnat hjälpa nØllan med att smuggla vapen, men utan dem kan jag inte göra kesselloppet. Tror dock att Gallandro känner någon skum typ som kanske kan hjälpa er, både med vapen och att smuggla det till rebellbasen. Han brukar hänga till i Roche Asteroidbältet.",
			"comment" : "Den här ledtråden ger Chewbacca om nØllan hälsar på honom med wookieljud",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "Självklart har jag vapen att sälja, men inget är gratis här i livet. Vad gäller att smuggla dem till rebellerna så kan jag inte hjälpa er, men Brasck kanske kan. Han brukar hålla till i Correlian System. Han är en väldigt slimmig typ, men ge honom mitt business card så kommer han att hjälpa er.",
			"comment" : "Den här ledtråden ger Gallandro i Roches asteriodbälte om nØllan frågar om han säljer vapen/kan hjälpa dem med kessel run. Han säljer även något vapen i en kartong till dem för 500 krediter",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "När nØllan kommer till Brasck och Chief Muskov måste de lista ut vem de ska ge visitkortet till. Om nØllan råkar ge kortet till Muskov så ska han säga åt dem att det finns en skylt med instruktioner vid Endor. På skylten står det att nØllan tabbat till det och att de borde försöka igen. Ger de kortet till Brasck tar han med nØllan och visar dem banan för att racea den radiostyrda bilen. Han informerar om nuvarande banrekord, och informerar nØllan om att de kan vadslå krediter och vinna om de krossar banrekordet. När nØllan är klar med loppet stämplar Brasck paketet med en »laglig» stämpel. Har nØllan vadslagit och vunnit betalas vinsten ut här.",
		"requirements" : "Uppdraget redovisas genom att visa upp kartongen med vapnena i till rebellbasen, med stämpeln om att de har »lagligt» importerats.",
		"props" : "För det här uppdraget behövs 14 små kartonger för vapentransport, som Gallandro ska dela ut. Det behövs även 14 visitkort för Gallandro. Det behövs en stämpel eller markeringspenna för att sätta stämpel på smuggelgodset. Det behövs en radiostyrd bil eller liknande för att racea med, samt material för att markera ut en bana. Sist behövs det en skylt som sätts upp vid Endor, ifall nØllan ger visitkortet till cheif Muskov."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/1000arsservice.json
{
	"id" : "1000arsservice",
	"main" : {
		"title" : "1000-årsservice av Falken",
		"background" : "Falken har börjat hacka betänkligt den senaste tiden. Speciellt är det hyperdriven som inte verkar fungera som den ska... Minns med fasa senaste gången då nØllan var jagad av ett par asteroider och nØllan ville gå in i hyperrymden. Det resulterade i ett par rejäla bucklor i aktern och en och annan, inte så lite, spräckt bakruta då backen gick i istället. Falken är numera belagd med körförbud, och för att nØllan skall kunna genomgå Jedi-träning lååångt borta måste den repareras.",
		"goal" : "nØllan måste hitta en mekaniker dum nog att vilja försöka reparera Falken. Dessutom kommer det antagligen att behövas en och annan reservdel till skrothögen.",
		"reward" : "Belöningen kommer, förutom ett fungerande (nåja) rymdskepp, troligtvis att bli en ömmande plånbok.",
		"hint" : "Boba Fett fick sin rymdmoped saboterad förra veckan och att han var tvungen att reparera den. Ta er till Wild Space och fråga Boba Fett om han känner någon bra mekaniker."
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "Jag reparerade min rymdmoped hos mekanikern Deppo i Junkfort Station vid Nar Shaddaa.",
			"comment" : "Den här ledtråden ger Boba Fett i Wild Space muntligen om nØllan frågar honom om hans rymdmoped eller var man kan hitta en mekaniker.",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "Det enda som behövs är en ny »hyperdrive motivator». Skaffa en åt mig så kan jag laga ert skepp. R2D2 vet förmodligen var ni kan få tag på en. Sist jag såg R2D2 var han i baren i Mos Eisley.",
			"comment" : "Den här ledtråden ger Deppo i Junkfort Station muntligen om nØllan frågar om han kan reparera Falken.",
			"characters" : []
		},
		{
			"id" : "3",
			"text" : "Det var ett par jawas från Tatooine som drog förbi med ett antal robotar på släp för tre månar sedan...",
			"comment" : "Den här ledtråden ges av barpersonalen i Mos Eisley och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "4",
			"text" : "Här i trakterna finns det inte så många köpare, så vi lät vår vän Albeback ta robotarna norrut, han bör inte hunnit ut ur Correlia System än...",
			"comment" : "Den här ledtråden ges av Jawas på Tatooine och trycks på ett »Hitta R2D2»-ledtrådskort (via r2d2.json) så att de inte skall behöva fråga vilket uppdrag nØllan håller på med.",
			"characters" : []
		},
		{
			"id" : "5",
			"text" : "Tydligen har Chewbacca också varit på vift i stjärnrymden och letat efter en hyperdrive motivator. Men han verkar visst ha blivit distraherad av några cyber-synthar. Gå till karaokebaren i södra delen av Correlia System och hjälp honom!",
			"comment" : "Den här ledtråden ges av R2D2 om man skriver in koden »hyperdrive motivator».",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "Vid plats 54 har Chewie åtta stycken papperflyplan med texten »hyperdrive motivator». Varje flygplan är märkt med ett serienummer (E139GI485993, G293MER3984, IOP235667980, PLAN7146387, VIGG2988756, NO123495MN, FR0GG298347, SLAV12457690, GOOG2203452, KLÄG253401G, GMHRL249D14, NLS50106Q40, TJOS0256KFD). Det enda nØllan behöver göra är hjälpa Chewie sjunga en duo i SingStar för att få flygplanet, sen kan de gå till Junkfort Station med det och ge det till Deppo. Efter att ha fått reservdelen och efter att han kontrollerat att den är autentisk, kräver Deppo 1000 krediter för att laga Falken och det är bara för nØllan att hysta upp alltsammans för att klara uppdraget. När Deppo fått pengarna signerar han pappersflygplanet som bevis på att nØllan klarat uppdraget.",
		"requirements" : "Uppdraget redovisas genom att visa upp sitt papperflygplan komplett med Deppos signatur i rebellbasen.",
		"props" : "För det här uppdraget behövs åtta stycken pappersflygplan märkta med texten »hyperdrive motivator» samt med unika serienummer (E139GI485993, G293MER3984, IOP235667980, PLAN7146387, VIGG2988756, NO123495MN, FR0GG298347, SLAV12457690, GOOG2203452, KLÄG253401G, GMHRL249D14, NLS50106Q40, TJOS0256KFD). En lista med dessa serienummer skall finnas hos Deppo i Junkfort Station så att han kan pricka av varje plan som kommer in så att nØllan inte tillverkar egna. Utöver pappersflygplanen behövs Deppo själv och Chewbacca samt en fungerande R2D2 med tillhörande vakter, barpersonalen i Mos Eisley och Jawas på Tatooine (är inte enbart för det här uppdraget). Utöver det krävs ett SingStar."
	}
}

=== datasektionen/hurryscurry/resources/rpu/data/missions/solo.json
{
	"id" : "solo",
	"main" : {
		"title" : "Befria Han Solo",
		"background" : "Han Solo är skyldig rymdfettot Jabba the Hutt en stor summa pengar. Detta har gjort honom väldigt efterlyst och numera väldigt försvunnen. Leias intensiva uppvaktning har lämnat honom helt kall. Han Solo är den enda som kan flyga Falken och ni måste hitta honom innan den fasansfulla Jabba the Hutt schlemar ner honom.",
		"goal" : "nØllan måste hitta Han Solo snabbt. (nØllan hinner dock säkert ta sig en Hutt innan nØllan träffar Jabba)",
		"reward" : "Detta uppdrag är värt 1600 krediter och dessutom Han Solos eviga tacksamhet.",
		"hint" : "Som mekaniker får man ofta höra ett och annat när rymdskepp kommer in för reparation efter något storartat äventyr. Snacka med Deppo som håller till i Junkfort Station i närheten av Nar Shaada, och se om han har någon aning om var Han kan ha tagit vägen."
	},
	"clues" : [
		{
			"id" : "1",
			"text" : "Jag vet inte var Han Solo hålls fången, men jag har hört rykten om att det krävs en hemlig kod för att komma in i cellen. Om ni hittar koden kanske ni även kommer över cellens position. Leta reda på Luke, och fråga om han har koll på när Han Solo hade sin svensexa, jag tror att det datumet kan vara den första delen av koden. Ni hittar honom i hålet vid Wild Space.",
			"comment" : "Ledtråden ges av Deppo om man frågar om Han Solo.",
			"characters" : []
		},
		{
			"id" : "2",
			"text" : "När nØllan kommer förbi och frågar om svensexan känner du nostalgi kring den, men känner dig lite väl ledsen över att Han är borta för att kunna den där koden som nØllan vill ha till Han Solos fängelse. När nØllan ger dig en tillräckligt bra komplimang skiner du upp ger ut koden 750 samt att Boba Fett i Wild Space vet mer. KOM IHÅG DEN KODEN!!",
			"comment" : "Efter komplimangen ger Luke det rätta svaret (750).",
			"characters" : []
		},
		{
			"id" : "3",
			"text" : "Svensexa. Juste, vi drog till Ice-bar! Jarjar och Joe Exotic drog hem tidigt, klena som de är. Luke hittade en riktigt snygg wookiebrud och drog hem, så det var bara jag och Han Solo kvar. Sen fastnade Han Solo med tungan på en vägg. Så jag gick hem, ingen har sett honom sedan dess. Konstigt. Ni kan hitta Ice-bar, som också går under namnet Cryochamber 5, i Corellia System.",
			"comment" : "Ges av Boba Fett som börjar prata om svensexan när de nämner svensexan och mutar honom med 500 krediter.",
			"characters" : []
		}
	],
	"meta" : {
		"resolution" : "När nØllan kommer till Cryo-chamber 5 frågar vakterna om koden (750). Vid korrekt kod klagar vakten på att det är så tråkigt att vakta den nedfrysta Han Solo. Hen deklarerar sedan att nØllan först måste podrace:a med hen innan de kan bli insläppta till Han Solo. Vakten tar då med nØllan ut till parkeringen utanför D-huset (gå ut genom utgången vid Örådet) och race:ar med sparkcyklarna. Efter racet återvänder de till Cryochamber 5 och inne i rummet står en stor frysbox innehållandes 13 stycken isblock. Vakten ser till att nØllan bara tar ett av dessa. I isblocken ligger »Frysvara»-lappar  varav en är den riktiga Han Solo och de andra 12 Han Solos bröder istället. När nØllan valt isblock tinar de upp det till exempel genom att spola varmt vatten på det inne på närmaste toalett. Han Solo är befriad.",
		"requirements" : "Uppdraget redovisas genom att laget går till Rebellbasen med med den Solo-broder som de tinade upp och visar upp honom. Om det är Han Solo så kan nØllan inkassera hela belöningen på 1600 krediter, men om det inte är han så får nØllan bara 1200.",
		"props" : "På det här uppdraget behövs en del saker som tar lite tid att fixa. Det behövs en vakt till dörren som kan släppa in nØllan, samt innehar två sparkcyklar. Inuti rummet skall det stå en frysbox och i den skall det finnas 13 stycken isblock med Solo-bröder. Isblocken tillverkas enkelt genom att fylla ett matlådor till hälften med vatten eller ännu hellre saft (det kan gå att läsa texten genom vatten), frysa, lägga i en Solo, fylla resten av paketet och till sist frysa det nya vattnet. Processen kan ta något dygn eller två så det är bra att börja i tid. Solo-bröderna utgörs av 13 stycken lappar märkta med »Frysvara» för Han Solo och hans bröder Hans Olof, Jan Solo, Lots Todo, Hans Aaro, Hen Solo, Han Solveig, Dan Solo, San Holo och Olos Nah, Fan Yolo, Steve Polo och Khan Jell-O. Lapparna finns som i mappen »Frysvara» under »Trycksaker» i Hurry Scurry-mappen och bör plastas in annars blir de förstörda när de ska frysas in. Frysboxen skall vaktas av minst en person som ser till att nØllan bara väljer ett isblock och inte gör sig av med själva isen genom att till exempel kasta isblocket i väggen. Vidare krävs också att personen som spelar Boba Fett är informerad om vad han eller hon skall säga och på plats i Wild Space (se kartan), lika så gäller för Luke. Det behövs också handsprit till Han Solo vakten för när de ska racea"
	}
}
