<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules [
<!ELEMENT rules (mission, event*, role*, resource*)>
<!ELEMENT mission (name, description, proof, reward, checkpoint*, resource*, dependency*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT proof (#PCDATA)>
<!ELEMENT reward (#PCDATA)>
<!ELEMENT checkpoint (name)>
<!ELEMENT dependency (mission+)>
<!ELEMENT event (name, description)>
<!ELEMENT role (name, checkpointref*)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT checkpointref (#PCDATA)>

<!ATTLIST mission missionID ID #REQUIRED>
<!ATTLIST checkpoint checkpointID ID #REQUIRED>
<!ATTLIST dependency required  CDATA #REQUIRED>
<!ATTLIST event eventID ID #REQUIRED>
<!ATTLIST role admin CDATA #REQUIRED>
<!ATTLIST resource type CDATA #REQUIRED>
]>

<rules>

  <!-- All missions -->
  <mission missionID="dodsstjarnan">
    <name>Förstör Dödsstjärnan</name>
    <description>Imperiet har länge slipat på sitt senaste, inte så lite farliga vapen; Dödsstjärnan. Nu står deras verk inför fullbordans rand. Inom en inte alltför lång tid kommer kejsaren att ge order till sina horder att inviga detta vapen genom att bjuda en slumpmässigt vald oskyldig planet på en hejdundrande fyrverkerishow.</description>
    <proof>nØllan kommer minst sist!</proof>
    <reward>nØllans belöning kommer vara, förutom evig ära och berömmelse, en snabb placering som minst sist i Hurry Scurryn.</reward>
    <checkpoint checkpointID="foundDeathstar">
      <name>Hittat Dödstjärnan</name>
    </checkpoint>
    <resource type="backgroundImage">deathstar.jpg</resource>

    <dependency required="4">
      <mission missionID="wmd">
        <name>Införskaffa WMD</name>
        <description>Kriget har nu pågått tämligen rymdlänge och nØllans vapenarsenal börjar tryta. Den sista laserkatapulten gick sönder igår, till och med jonknivarna har blivit slöa och börjat rosta. Det enda vapen som återstår är gummisnoddarna. På sistone har dock Stormtroopers utvecklat rustningen Kevlar Mark III-b som är i stort sett immuna mot gummivapen. Rykten gör gällande att en ljusskygg vapenhandlare säljer ritningarna till ett nytt särdeles kraftfullt vapen som definitivt skulle ge rebellerna en större chans i slaget.</description>
        <proof>Uppdraget redovisas genom att nØllan tar med sig sin nyinköpta ritning och intyg och visar dem i rebellbasen.</proof>
        <reward>nØllans belöning för detta uppdrag kommer inte att bestå av några krediter (giriga nØllan!). Ritningen till ett, inte så lite, potent vapen är belöning nog.</reward>
        <checkpoint checkpointID="soldBomb">
          <name>Köpt bomben</name>
        </checkpoint>
        <resource type="backgroundImage">bomb.jpg</resource>
      </mission>

      <mission missionID="kraftfalt">
        <name>Dödsstjärnans Kraftfält</name>
        <description>Många är de rebeller som tappat huvudet och skadat sig svårt vid attacker mot Dödstjärnan. Sällan har det berott på bristande planering eller sviktande mod hos piloterna. Nej, allt som oftast har uppdragen gått åt fanders på grund av det inte så lite farliga kraftfält som omger det monstruösa bygget.</description>
        <proof>nØllan avsöjar den hemliga koden för att deaktivera kraftfältet för rebellerna.</proof>
        <reward>Förutom att den hemskaste av hemska stjärnor snart kommer ligga öppen för dissekering kommer nØllans belöning bestå av fett stort hål i plånboken.</reward>
        <checkpoint checkpointID="foundEwok">
          <name>Hittat Ewokerna</name>
        </checkpoint>
        <resource type="backgroundImage">forcefield.jpg</resource>

        <dependency required="1">
          <mission missionID="c3po">
            <name>Hitta C3P0</name>
            <description>Det finns många språk i rymden, detta har lett till ett och annat missförstånd genom åren. Tolkrobotar uppfanns för att råda bot på detta och en av de mest sympatiska av dessa plåtburkar är C3PO. Han har dessutom en förkärlek för att gå i små bitar. nØllan kan tänkas träffa på saker i rymden som nØllan inte förstår och då kan C3PO komma väl till pass.</description>
            <proof>Uppdraget redovisas genom att visa upp en komplett och ihopsatt C3PO i rebellbasen. Om det är lag »C3PO» som klarat uppdraget får de 1000 krediter som belöning.</proof>
            <reward>nØllans belöning är, förutom ett mycket trevligt sällskap långa mörka vinterkvällar, en mycket användbar översättare.</reward>
            <checkpoint checkpointID="c3p0Part">
              <name>Hittat C3P0 del</name>
            </checkpoint>
            <resource type="backgroundImage">brokenc3po.jpg</resource>
          </mission>
        </dependency>
      </mission>

      <mission missionID="kenobi">
        <name>Sök upp Obi-Wan Kenobi</name>
        <description>Obi-Wan Kenobi är en mycket vis och lärd man. Av honom kan nØllan lära sig mycket. Obi-Wan är dessutom en Jedi-riddare, något som nØllan drömmer om att bli. För att kunna bli en stor och präktig Jedi så behövs förutom ett glatt humör och oömma kläder även en skarpslipad ljussabel.</description>
        <proof>Uppdraget redovisas genom att visa upp sin ljussabel i rebellbasen.</proof>
        <reward>Skäms, giriga nØllan! Att bli en Jedi är inget man gör för ära eller pengar, det är ett kall. Fast å andra sidan är det ju rätt häftigt att ha Kraften och den är ju inte så mycket att ha utan en ljussabel, eller hur?</reward>
        <checkpoint checkpointID="foundLight">
          <name>Fått ljusabel</name>
        </checkpoint>
        <resource type="backgroundImage">benkenobi.jpg</resource>
      </mission>

      <mission missionID="jeditraning">
        <name>Genomgå Jediträning</name>
        <description>För att nØllan ska ha en chans att klara av allt som en rebell kan stå inför så måste nØllan träna för att bli en Jedi-riddare. Det finns en liten konstig krumelur vid namn Yoda som vet ganska mycket om detta. nØllan måste hitta denna man för att få instruktioner och utbildning. Om nØllan lyssnar noga kanske nØllan kan lära sig något om Kraften.</description>
        <proof>Uppdraget redovisas genom att nØllan går tillbaka till rebellbasen och stolt visar upp sina batterier.</proof>
        <reward>Om nØllan lyckas så belönas nØllan med den inte så lite värdefulla kraften.</reward>
        <checkpoint checkpointID="foundDagobah">
          <name>Hittat Dagobah</name>
        </checkpoint>
        <checkpoint checkpointID="gotForce">
          <name>Fått kraften</name>
        </checkpoint>
        <resource type="backgroundImage">jedi.jpg</resource>

        <dependency required="1">
          <mission missionID="1000arsservice">
            <name>1000-årsservice på falken</name>
            <description>Falken har börjat hacka betänkligt på senaste tiden. Speciellt är det hyperdriven som inte verkar fungera som den ska... Minns med fasa den senaste gången då nØllan var jagad av ett par asteroider och nØllan ville gå in i hyperrymden. Det resulterade i ett par rejäla bucklor i aktern och en och annan, inte så lite, spräckt bakruta eftersom backen gick i istället. Falken är numera belagd med körförbud, och för att nØllan ska kunna genomgå Jedi-träning lååångt borta måste den repareras.</description>
            <proof>Uppdraget redovisas genom att visa upp sitt papperflygplan komplett med Deppos signatur i rebellbasen.</proof>
            <reward>Belöningen kommer, förutom ett fungerande (nåja) rymdskepp, troligtvis att bli en ömmande plånbok.</reward>
            <checkpoint checkpointID="findMotivator">
              <name>Ska hitta Hyperdrive motivator</name>
            </checkpoint>
            <checkpoint checkpointID="gotMotivator">
              <name>Hittat platsen för Hyperdrive motivator</name>
            </checkpoint>
            <resource type="backgroundImage">falcon.jpg</resource>
          </mission>
        </dependency>

      </mission>
    </dependency>

    <dependency required="2">
      <mission missionID="ritningar">
        <name>Hemliga ritningar</name>
        <description>Ett gäng tappra rebeller har kommit över ritningar till Dödsstjärnan, närmare bestämt de ritningar som exponerar dess svagheter. Tyvärr lyckades de inte sända ritningarna särskilt långt från Scarif då rymdspionen Latara kom över dem. Rebellbasen är i stort behov av dessa ritningar för att kunna oskadliggöra detta fruktansvärda vapen!</description>
        <proof>Uppdraget redovisas genom att nØllan visar upp ritningarna på Wookieleaks.org samt intygen som skall ha (minst) två stämplar (över checkrutorna &quot;Inspektion utförd&quot; samt &quot;Objekt godkänt&quot;) i rebellbasen.</proof>
        <reward>Om nØllan lyckas med det här uppdraget så belönas nØllan med 1000 krediter.</reward>
        <resource type="backgroundImage">battlePlan.jpg</resource>
      </mission>

      <mission missionID="smuggelgods">
        <name>Hitta smuggelgodset</name>
        <description>Rebellerna har sedan en tid haft kännedom av att en av Darth Vaders mest kära ägodelar smugglas genom galaxen. Rebellerna vet inte vad det är men denna ägodel har förflyttas små sträckor åt gången för att inte väcka uppmärksamhet. Ryktet går att detta åtråvärda objekt endast är ett stenkast ifrån rebellbasen, och det är nu hög tid för att lägga vantarna på paketet!</description>
        <proof>Uppdraget redovisas genom att nollan visar upp paketet i rebellbasen.</proof>
        <reward>nØllan belönas med 1000 krediter för ett väl genomfört uppdrag.</reward>
        <resource type="backgroundImage">findGoods.jpg</resource>
      </mission>

      <mission missionID="stridsteknik">
        <name>Ny stridsteknik</name>
        <description>Jedi-riddarna har stridit mot Imperiet länge och deras teknik är välkänd av den Mörka Sidan. För att rebellerna fortfarande ska kunna utgöra ett hot måste de hitta nya sätt att strida på. Ryktet går att rymdpiraten och wärdshusägaren Maz Kanata har en effektiv stridsteknik att lära ut.</description>
        <proof>Uppdraget redovisas genom att nØllan visar upp en bild där de utför dansen framför en Stormtrooper (som på något sätt visar att de är rädda för dansen och tappar popcorn).</proof>
        <reward>Som om inte stridstekniken vore belöning nog så får nØllan även 1000 krediter för väl genomfört uppdrag.</reward>
        <resource type="backgroundImage">battleTech.jpg</resource>
      </mission>

      <mission missionID="leia">
        <name>Rädda Prinsessan Leia</name>
        <description>Prinsessan Leia Organa har blivit tillfångatagen av en Imperial Star Destroyer. Skeppet fördes av Darth Vader i egen hög person. Hon stoppades när hon var på väg till Obi-Wan Kenobi för att övertala honom att samarbeta med rebellerna. Hon har sett ritningarna till dödsstjärnan och är dessutom en riktig snygging.</description>
        <proof>nØllan uppvisar ett pussmärke från Prinsessan Leias läckra läppar på en av lagmedlemmarnas kind.</proof>
        <reward>Om nØllan lyckas med det här uppdraget så belönas nØllan med, utöver prinsessan Leias gunst, 1100 krediter.</reward>
        <resource type="backgroundImage">freeleia.jpg</resource>
      </mission>

      <mission missionID="solo">
        <name>Befria Han Solo</name>
        <description>Han Solo är skyldig rymdfettot Jabba the Hutt en stor summa pengar. Detta har gjort honom väldigt efterlyst och numera väldigt försvunnen. Leias intensiva uppvaktning har lämnat honom helt kall. Han Solo är den enda som kan flyga Falken och ni måste hitta honom innan den fasansfulla Jabba the Hutt schlemar ner honom.</description>
        <proof>Uppdraget redovisas genom att laget går till Rebellbasen med med den Solo-broder som de tinade upp och visar upp honom. Om det är Han Solo så kan nØllan inkassera hela belöningen på 1600 krediter, men om det inte är han så får nØllan bara 1200.</proof>
        <reward>Detta uppdrag är värt 1600 krediter och dessutom Han Solos eviga tacksamhet. 1200 krediter om de tar fel broder.</reward>
        <checkpoint checkpointID="cryochamber">
          <name>Hittat cryochamber</name>
        </checkpoint>
        <checkpoint checkpointID="choosenBrother">
          <name>Räddat Solo</name>
        </checkpoint>
        <resource type="backgroundImage">freesolo.jpg</resource>
      </mission>

      <mission missionID="prisjagare">
        <name>Prisjägare</name>
        <description>Sedan huvudjägarna råkade åka vilse i hyperrymden finns det alltid för få prisjägare. Att mot betalning hämta in åtråvärda personer är tillräckligt lukrativt för att det flesta med kapacitet nog åtar sig såna uppdrag.</description>
        <proof>Uppdraget redovisas genom att nØllan lämnar in kålhuvudet i rebellbasen.</proof>
        <reward>Belöningen består av, förutom känslan av att utfört ett hyggligt dagsverke, 2000 krediter.</reward>
        <checkpoint checkpointID="startHunt">
          <name>Jagar Joruus C'baoth</name>
        </checkpoint>
        <checkpoint checkpointID="foundHideout">
          <name>Hittat Joruus C'baoth's gömställe</name>
        </checkpoint>
        <resource type="backgroundImage">bountyhunters.jpg</resource>
      </mission>

      <mission missionID="kryddor">
        <name>Smuggla kryddor</name>
        <description>I den rymd som hårt kontrolleras av Kejsarens lakejer finns det allt färre möjligheter att tjäna en ärlig hacka. Smugglingen har länge varit ett sätt för många att dryga ut hushållskassan. Nyligen kom ett Kejserligt förbud enligt vilket det blivit förbjudet att krydda maten.</description>
        <proof>Uppdraget redovisas genom att visa upp sitt uppdragskort i rebellbasen signerat av kryddsmugglaren Brasck. Om det är lag »Lando Calrissian» som kommer tillbaka med ett signerat uppdragskort så får laget ytterligare 1000 krediter (utöver det som Brasck redan har betalat) eftersom det är deras favorituppdrag</proof>
        <reward>Belöningen till nØllan kommer att, förutom glädjen i att veta att tusentals familjer återigen kommer kunna krydda sin mat, bestå av 1200 krediter som delas ut av Brasck.</reward>
        <checkpoint checkpointID="gotSpice">
          <name>Hämtat kryddorna</name>
        </checkpoint>
        <checkpoint checkpointID="leftSpice">
          <name>Lämnat Kryddorna</name>
        </checkpoint>
        <resource type="backgroundImage">spices.jpg</resource>
      </mission>

      <mission missionID="luke">
        <name>Hjälp Luke</name>
        <description>Luke Skywalker har en dålig ovana att försöka rädda Rymdprinsessor och därigenom hamna i knipa. Nu har han återigen hamnat i knipa och ramlat ned i ett sopnedkast! Om det inte var nog illa att han följde med resterna av sin McStar-meny när han skulle kasta den så håller väggarna sakta men säkert på att mosa honom lika platt som Darth Vaders plånbok efter att han har köpt en påse hallon/lakrits-skallar en vanlig lördag kväll. Ni måste kvickt rädda Luke från detta hemska öde!</description>
        <proof>Uppdraget redovisas genom att nØllan visar upp tack-kortet för personalen i rebellbasen.</proof>
        <reward>nØllan kan inkassera 800 krediter efter ett väl genomfört uppdrag.</reward>
        <checkpoint checkpointID="stoppedPress">
          <name>Stoppat pressen</name>
        </checkpoint>
        <resource type="backgroundImage">fixluke.jpg</resource>
      </mission>
    </dependency>
  </mission>

  <!-- All negative events -->
  <event eventID="asteroides">
    <name>Asteroider! (neg)</name>
    <description>
			Ni har gjort ett misslyckat hopp i hyperrymden. Felaktiga
			koordinater ledde till att ni hamnade mitt i ett
			asteroidfält. Detta innebär massiva reparationskostnader.
			Leta upp den skickliga ingenjören Deppo som håller till i
      Junkfort Station, vid Nar Shaddaa (dyrt nØllan).
    </description>
  </event>

  <event eventID="epidemic">
    <name>Epidemi (neg)</name>
    <description>Din förste styrman upptäcker till sin förskräckelse att han har fått slut på mjällschampo. Om du inte genast fyller på lagret så hotas hela skeppet av mjällepidemi. Hitta handelsresande Gallandro i Roche Asteroid-bälte och köp mera schampo.</description>
  </event>

  <event eventID="starvation">
    <name>Svält ombord (neg)</name>
    <description>
			Din förste styrman har gjort slut på sitt förråd av
			&quot;VoV&quot; och slickar förtvivlat i hundskålen istället
			för att styra skeppet. Bege dig till rymdfånen Latara i
			Cloud City och köp mera hundmat.
    </description>
  </event>

  <event eventID="jamming">
    <name>Jammade vapen (neg)</name>
    <description>Din förste skytt har fastnat med tandställningen i slutsycket till laserkanonen, detta försvårar målsökning på rörliga mål. Tala med Deppo i Junkfort Station, vid Nar Shaddaa.</description>
  </event>

  <event eventID="bribes">
    <name>Mutor! (neg)</name>
    <description>Du glömde stanna vid den röda jättestjärnan och rymdtrafikpolisen haffar dig i en rutinkontroll. Du måste muta dem för att slippa betala böterna. Ge mutan till Chief Muskov i ljusgården i Corellia System. På platsen finns en person till, nämligen kryddsmugglaren Brasck. Du måste muta rätt person. Tänk på följande: Brasck ljuger alltid, medan Chief Muskov alltid talar sanning. De kan bara svara på ja- och nej-frågor.</description>
  </event>

  <event eventID="kidnapping">
    <name>Kidnappning (neg)</name>
    <description>Skeppets förstestädare har blivit kidnappad av illvilliga Kowakianska Apödlor. Detta har lett till att skeppets interna volym har halverats på grund av allt skräp. Betala lösen till rymdskurken Big Bunji som brukar hålla till vid baren i Mos Eisley.</description>
  </event>

  <event eventID="delays">
    <name>Förseningar (neg)</name>
    <description>Ni har glömt att lämna tillbaks videofilmen &quot;Tjejen som beamades för mycket&quot;. Dessutom har ni av misstag flugit ett okänt antal år in i framtiden. Förseningsavgiften blir inte nådig. Leta reda på Big Bunji i baren i Mos Eisley så får ni veta hur nådig den inte blir.</description>
  </event>

  <event eventID="wounds">
    <name>Skador (neg)</name>
    <description>Er förste styrman har på fyllan utmanat Jabba the Hut på en sumo-match. Detta var ett stort misstag. Det är känt att Deppo på Junkfort Station, vid Nar Shaddaa, är bevandrad i första hjälpen, men det blir inte billigt nØllan.</description>
  </event>

  <!-- All positive events -->
  <event eventID="wanted">
    <name>Efterlyst (pos)</name>
    <description>Du skymtar den efterlyste Xim the Despot när han flyr in på ett utedass på planeten Churba. Denna information är värd pengar. Rapportera detta till Chief Muskov, som håller till i ljusgården i  Corellia System, och tjäna en hacka. Se upp så ni inte ger informationen till fel person (Brasck) för då får ni inga krediter alls. Chief Muskov talar alltid sanning, och Brasck ljuger konsekvent. Båda kan bara svara på ja- och nej-frågor.</description>
  </event>

  <event eventID="jeopardy">
    <name>Jeopardy (pos)</name>
    <description>Gå in på baren i Mos Eisley och säg &quot;Vem i helvete är Arhul Hextrophon?&quot;, och inkassera förstapriset i Stjärn-Jeopardy.</description>
  </event>

  <event eventID="talent">
    <name>Sångartalang (pos)</name>
    <description>Du får ett erbjudande att bli solosångare i Max Rebo's jizz-wailing band då den ordinarie lead-sångaren Sy Snootles har blivit täppt i näsan. Bege dig till Mos Eisley och provsjung för barpersonalen för att tjäna en hacka.</description>
  </event>

  <event eventID="sniper">
    <name>Sprickskytt (pos)</name>
    <description>En av dina besättningsmän har vunnit den årliga prickskyttetävlingen &quot;Sikta mot Stjärnorna&quot;. Imponera på Boba Fett i Wild Space genom att visa honom detta kort.</description>
  </event>

  <event eventID="humor">
    <name>Tråkig humor (pos)</name>
    <description>Rymdfånen Latara i Cloud City är känd för att ha en mycket torftig humor. Dra en godtycklig vits som innehåller orden &quot;tomat&quot; och &quot;går vi&quot; för henne så kommer ni att bli rikligt belönade.</description>
  </event>

  <event eventID="slogan">
    <name>Space'R'Us (pos)</name>
    <description>Du har vunnit en slogan-tävling med bidraget &quot;Om det ryms I rymden så säljer vi det&quot; till hårdvarujätten Space'R'Us. Inkassera priset från handelsresande Gallandro I Roche Asteroidbälte.</description>
  </event>

  <event eventID="longnose">
    <name>Långnäsa (pos)</name>
    <description>Ni har blivit lurade av den legendariske rymdfånen Latara. Hon har sålt er hudkräm med vitamintillskott som inte alls uppfyllde det som utlovades i reklamen. Gå till Latara i Cloud City och kräv pengarna tillbaka.</description>
  </event>

  <!-- All roles -->
  <role admin="true">
    <name>Rebel base</name>
  </role>

  <role admin="false">
    <name>R2D2 Vakt</name>
    <checkpointref>leiaCell</checkpointref>
    <checkpointref>gotMotivator</checkpointref>
    <checkpointref>foundHideout</checkpointref>
    <checkpointref>foundDecoder</checkpointref>
    <checkpointref>foundArm</checkpointref>
    <checkpointref>foundDagobah</checkpointref>
  </role>

  <role admin="false">
    <name>Obi-wan Kenobi</name>
  </role>

  <role admin="false">
    <name>Ewok</name>
    <checkpointref>foundEwok</checkpointref>
  </role>

  <role admin="false">
    <name>Deppo</name>
    <checkpointref>findMotivator</checkpointref>
  </role>

  <role admin="false">
    <name>Latara</name>
  </role>

  <role admin="false">
    <name>Brask</name>
  </role>

  <role admin="false">
    <name>BigBunji</name>
  </role>

  <role admin="false">
    <name>Bobba Fett</name>
  </role>

  <role admin="false">
    <name>Stormtrooper</name>
  </role>

  <role admin="false">
    <name>Han-Solo vakt</name>
  </role>

  <role admin="false">
    <name>Leia</name>
  </role>

  <role admin="false">
    <name>Mos Eisley</name>
    <checkpointref>gotSpice</checkpointref>
  </role>

  <role admin="false">
    <name>Gallandro</name>
    <checkpointref>soldBomb</checkpointref>
  </role>

  <role admin="false">
    <name>Yoda</name>
  </role>

  <role admin="false">
    <name>Latara</name>
    <checkpointref>foundDeathstar</checkpointref>
  </role>

  <role admin="false">
    <name>Coyote (Övrig)</name>
  </role>

  <!-- Overall resources - for the whole client -->
  <resource type="backgroundImage">bigBackground.jpg</resource>
  <resource type="titleFont">SF Distant Galaxy Outline.ttf</resource>

  <!-- Resources for the team info panel -->
  <resource type="teamInfoTopCap">teamInfoTopCap.png</resource>
  <resource type="teamInfoBottomCap">teamInfoBottomCap.png</resource>
  <resource type="teamInfoLeftCap">teamInfoLeftCap.png</resource>
  <resource type="teamInfoRightCap">teamInfoRightCap.png</resource>
  <resource type="teamInfoCellBackground">teamInfoCellBackground.png</resource>
  <resource type="teamInfoDivider">teamInfoDivider.png</resource>
  <resource type="teamProgressBarEmpty">teamProgressBarEmpty.png</resource>
  <resource type="teamProgressBarFull">teamProgressBarFull.png</resource>

  <resource type="negEventIcon">negEvent.png</resource>
  <resource type="negEventCompletedIcon">negEventCompleted.png</resource>

  <!-- Medals. Shared by MissionCell and TeamInfoCell atm. -->
  <resource type="goldMedalIcon">goldMedal.png</resource>
  <resource type="silverMedalIcon">silverMedal.png</resource>
  <resource type="bronzeMedalIcon">bronzeMedal.png</resource>

  <!-- The checkpoint icon, show in a team view MissionCell -->
  <resource type="checkpointIcon">checkpointIcon.png</resource>

  <!-- Status bar icons -->
  <resource type="chatChangedIcon">exclamation.png</resource>
  <resource type="connectionLostIcon">stop.png</resource>

  <!-- Other background images -->
  <resource type="helpBackgroundImage">helpbg.jpg</resource>
  <resource type="chatBackgroundImage">chatbg.jpg</resource>

  <!-- Help text files -->
  <resource type="helpTextFunk">help_funk.txt</resource>
  <resource type="helpTextn0llan">help_n0llan.txt</resource>
  <resource type="helpTextRebelBase">help_rebelbase.txt</resource>
</rules>
