<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE teams [
<!ELEMENT teams (team+)>
<!ELEMENT team (name, firstMission?, resource*, phonenumber?, member*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT firstMission (#PCDATA)>
<!ELEMENT phonenumber (#PCDATA)>
<!ELEMENT member (#PCDATA)>
<!ELEMENT resource (#PCDATA)>

<!ATTLIST team teamID ID #REQUIRED>
<!ATTLIST resource type CDATA #REQUIRED>

]>

<teams>
<team teamID="Aladdin">
<name>Aladdin</name>
<firstMission>smuggleSpices</firstMission>
<resource type="backgroundImage">AdmiralAck.png</resource>
<resource type="teamLogo">ackbarFace.png</resource>
<phonenumber>4711</phonenumber>
<member>Nollan1</member>
<member>Nollan2</member>
<member>Nollan3... NOLLAN!</member>
</team>

<team teamID="Bamse">
<name>Bamse</name>
<firstMission>findPlan</firstMission>
<resource type="backgroundImage">jarjarbinks.png</resource>
<resource type="teamLogo">jar_jar_binks.png</resource>
</team>

<team teamID="CruelladeVil">
<name>Cruella de Vil</name>
<firstMission>falcon</firstMission>
<resource type="backgroundImage">Chewbacca.jpg</resource>
<resource type="teamLogo">chewbaccaFace.png</resource>
</team>

<team teamID="Dolan">
<name>Dolan</name>
<firstMission>battleTech</firstMission>
<resource type="backgroundImage">darthvader_big.png</resource>
<resource type="teamLogo">darthvader_small.png</resource>
</team>

<team teamID="EnPokemon">
<name>En Pokemon</name>
<firstMission>genealogy</firstMission>
<resource type="backgroundImage">emperor_big.png</resource>
<resource type="teamLogo">emperor_small.png</resource>
</team>

<team teamID="FyrkantSvampbob">
<name>Fyrkant, Svampbob</name>
<firstMission>bountyHunter</firstMission>
<resource type="backgroundImage">BobaFett.jpg</resource>
<resource type="teamLogo">bobaFace.png</resource>
</team>

<team teamID="GrodanBoll">
<name>Grodan Boll</name>
<firstMission>findC3PO</firstMission>
<resource type="backgroundImage">grevious_big.png</resource>
<resource type="teamLogo">grevious_small.png</resource>
</team>

<team teamID="Hocaponas">
<name>Hocapontas</name>
<firstMission>freeLeia</firstMission>
<resource type="backgroundImage">Solo.jpg</resource>
<resource type="teamLogo">soloFace.png</resource>
</team>

<team teamID="IcaStig">
<name>Ica-Stig</name>
<firstMission>helpLuke</firstMission>
<resource type="backgroundImage">Stormtrooper_big.png</resource>
<resource type="teamLogo">Stormtrooper_small.png</resource>
</team>

<team teamID="JohnnyBravo">
<name>Johnny Bravo</name>
<firstMission>findGoods</firstMission>
<resource type="backgroundImage">jabbabig.png</resource>
<resource type="teamLogo">jabbatiny.png</resource>
</team>

<team teamID="KimPossible">
<name>Kim Possible</name>
<firstMission>findKenobi</firstMission>
<resource type="backgroundImage">ObiWanKenobi.jpg</resource>
<resource type="teamLogo">kenobiFace.png</resource>
</team>

<team teamID="LillaMy">
<name>Lilla My</name>
<firstMission>freeHanSolo</firstMission>
<resource type="backgroundImage">Leia.jpg</resource>
<resource type="teamLogo">leiaFace.png</resource>
</team>

<team teamID="MojoJojo">
<name>Mojo Jojo</name>
<firstMission>getBomb</firstMission>
<resource type="backgroundImage">MonMothma.jpg</resource>
<resource type="teamLogo">mothmaFace.png</resource>
</team>

</teams>
